.deploy-elasticsearch-to-k8s (dev):
  extends: .docker_kube_stage
  script:
    - /apps/create-kubeconfig.sh
    #
    - envsubst < k8s/elasticsearch/configmap-elasticsearch-dev.yml > ./configmap.yml
    - envsubst < k8s/elasticsearch/statefulset-elasticsearch-dev.yml > ./statefulset.yml
    - envsubst < k8s/elasticsearch/service-elasticsearch.yml > ./service.yml
    #
    - kubectl apply -f ./configmap.yml
    - kubectl apply -f ./statefulset.yml
    - kubectl apply -f ./service.yml


.deploy-elasticsearch-to-k8s (prod):
  extends: .docker_kube_stage
  script:
    - /apps/create-kubeconfig.sh
    #
    - envsubst < k8s/elasticsearch/statefulset-elasticsearch.yml > ./statefulset.yml
    - envsubst < k8s/elasticsearch/service-elasticsearch.yml > ./service.yml
    #
    - kubectl apply -f ./statefulset.yml
    - kubectl apply -f ./service.yml
