---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch${HASH_BRANCH_NAME}
  labels:
    app: elasticsearch${HASH_BRANCH_NAME}
    branch: ${BRANCH_NAME}
    commit: ${COMMIT}
    job: "${JOB_ID}"
spec:
  selector:
    app: elasticsearch${HASH_BRANCH_NAME}
  clusterIP: None
  ports:
  - port: ${ES_PORT}
    name: rest
  - port: ${ES_INTER_NODE}
    name: inter-node
