---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-${BRANCH_NAME}
  labels:
    app: elasticsearch-${BRANCH_NAME}
spec:
  selector:
    app: elasticsearch-${BRANCH_NAME}
  clusterIP: None
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
