---
kind: Service
apiVersion: v1
metadata:
  name: ${ELASTICSEARCH_HOST}
  labels:
    app: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  selector:
    app: ${ELASTICSEARCH_HOST}

  #

  clusterIP: None
  ports:
    - port: ${ES_PORT}
      name: rest
    - port: ${ES_INTER_NODE}
      name: inter-node
