---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ${ELASTICSEARCH_HOST}
  labels:
    app: ${ELASTICSEARCH_HOST}
    branch: cdtn${HASH_BRANCH_NAME}
spec:
  serviceName: ${ELASTICSEARCH_HOST}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${ELASTICSEARCH_HOST}
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: ${ELASTICSEARCH_HOST}
        resources:
          limits:
            memory: "640Mi"
            cpu: "1.5"
          requests:
            memory: "256Mi"
            cpu: "0.5"
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        image: ${CDTN_REGISTRY}/elasticsearch:${ELK_STACK_VERSION}
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-config${HASH_BRANCH_NAME}
              key: ES_JAVA_OPTS
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health
            port: ${ES_PORT}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: ${ES_PORT}
          initialDelaySeconds: 5
        ports:
        - containerPort: ${ES_PORT}
          name: es-http
        - containerPort: ${ES_INTER_NODE}
          name: es-transport
        volumeMounts:
        - name: es-data${HASH_BRANCH_NAME}
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config${HASH_BRANCH_NAME}
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-config${HASH_BRANCH_NAME}
        configMap:
          name: es-config${HASH_BRANCH_NAME}
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      - name: es-data${HASH_BRANCH_NAME}
        emptyDir: {}
