#
#
#

logger diff:
  stage: .pre
  extends:
    - .base_stage
  image: alpine:3.13
  cache:
    key:
      files:
        - yarn.lock
      prefix: logger-${CI_JOB_NAME}
    paths:
      - ${MONOREPO_CACHE_FOLDER}
    when: always
  before_script:
    - cd ${CI_PROJECT_DIR}
  script:
    - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
    - sh ./.gitlab-ci/monorepo.sh has-changed
        --find-ignore "*/node_modules/*"
        --verbose
        infra/logger || true
  artifacts:
    expire_in: 1 week
    paths:
      - ${MONOREPO_CACHE_FOLDER}/skip

logger build:
  stage: Prepare
  extends:
    - .base_stage
  image: node:14.16-alpine3.13
  needs:
    - job: logger diff
      artifacts: true
  cache:
    key:
      files:
        - yarn.lock
      prefix: logger-${CI_JOB_NAME}
    paths:
      - .cache
      - infra/logger/node_modules
      - infra/logger/lib
      - node_modules
    when: always
  before_script:
    - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
    - |
      sh ./.gitlab-ci/monorepo.sh skip && {
        rm -rf .cache/yarn infra/logger/node_modules node_modules;
        exit 0;
      } || true
    #
    - rm -rf infra/logger/lib;
    #
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
  script:
    - yarn exec yarn-workspace-focus-install -- --cwd infra/logger
    - cd infra/logger
    #
    - yarn build
    - yarn lint
    - yarn test
  artifacts:
    expire_in: 1 week
    paths:
      - infra/logger/lib

