extends:
  - "@socialgouv/eslint-config-react"

env:
  jest: true

settings:
  react:
    version: "16.0"

rules:
  prefer-const: 2
  no-console: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/label-has-for: off
  react/prop-types: off
