extends:
  - "@socialgouv/eslint-config-react"

rules:
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/label-has-for: off
  react/prop-types: off
  import/no-unresolved: [
    2,
    ignore: [
      wrapped-testing-library/react
    ]
  ]
  no-console: [
    "error",
    allow: [
      "warn",
      "error"
    ]
  ]

overrides:
  - files: ["*.test.js"]
    env:
      jest: true
