image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: master

deployment:
  port: ${PORT}

  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      # cpu: 5m
      memory: 128Mi

  livenessProbe:
    path: /api/v1/version
    failureThreshold: 6
    timeoutSeconds: 11
    periodSeconds: 16

  readinessProbe:
    path: /api/v1/version

  env:
    - name: ELASTICSEARCH_URL
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: url
    - name: ELASTICSEARCH_USER
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: user
    - name: ELASTICSEARCH_PWD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: password
    - name: ES_INDEX_PREFIX
      value: "cdtn-prod"
      # value: "cdtn-${BRANCH_HASH}"
    - name: NLP_URL
      value: "${NLP_URL}"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: api.code.travail.dev.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
        - api.code.travail.dev.fabrique.social.gouv.fr
      secretName: wildcard-crt
