image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: ${IMAGE_TAG}

fullnameOverride: "api-nodejs"

deployment:
  port: ${PORT}

  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 256Mi

  livenessProbe:
    path: /api/v1/version
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 4
  readinessProbe:
    path: /api/v1/version
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 4

  env:
    - name: ELASTICSEARCH_URL
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: url
    - name: ELASTICSEARCH_USER
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: user
    - name: ELASTICSEARCH_PWD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: password
    - name: ELASTIC_APM_SERVER_URL
      valueFrom:
        secretKeyRef:
          name: elastic-apm
          key: url
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-apm
          key: token
    - name: ES_INDEX_PREFIX
      value: "${ES_INDEX_PREFIX}"
    - name: ELASTIC_APM_SERVICE_NAME
      value: "cdtn-api"
    - name: ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME
      value: "true"
    - name: ELASTIC_APM_ENVIRONMENT
      value: "cdtn-${BRANCH_HASH}"
    - name: NLP_URL
      value: "${NLP_URL}"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"

service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: ${API_HOST}
      paths:
        - path: /
          servicePort: ${PORT}

  tls:
    - hosts:
        - ${API_HOST}
      secretName: api-crt

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUAverageUtilizationPercentage: 80
