image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: master

deployment:

  port: ${PORT}

  resources:
    limits:
      # cpu: 50m
      memory: 256Mi
    requests:
      # cpu: 5m
      memory: 128Mi

  livenessProbe:
    path: /api/v1/version
  readinessProbe:
    path: /api/v1/version

  env:
    - name: ELASTICSEARCH_LOG_LEVEL
      value: "trace"
    - name: ELASTICSEARCH_URL
      value: "${CI_ELASTICSEARCH_CLUSTER}"
    - name: ELASTICSEARCH_USER
      valueFrom:
        secretKeyRef:
          name: elasticsearch-creds
          key: user
    - name: ELASTICSEARCH_PWD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-creds
          key: password
    - name: ES_INDEX_PREFIX
      value: "cdtn-${BRANCH_HASH}"
    - name: NLP_URL
      value: "${NLP_API_URL}"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: api.code.travail.dev.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
        - api.code.travail.dev.fabrique.social.gouv.fr
      secretName: wildcard-crt
