image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: ${IMAGE_TAG}

fullnameOverride: "api-nodejs"

deployment:
  port: ${PORT}

  resources:
    limits:
      cpu: 100m
      memory: 320Mi
    requests:
      cpu: 100m
      memory: 320Mi

  livenessProbe:
    path: /api/v1/version
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 4
  readinessProbe:
    path: /api/v1/version
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 4

  env:
    - name: ELASTICSEARCH_URL
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: url
    - name: ELASTICSEARCH_USER
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: user
    - name: ELASTICSEARCH_PWD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-cloud-api
          key: password
    - name: ELASTIC_APM_SERVER_URL
      valueFrom:
        secretKeyRef:
          name: elastic-apm
          key: url
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-apm
          key: token
    - name: ES_INDEX_PREFIX
      value: "${ES_INDEX_PREFIX}"
    - name: ELASTIC_APM_SERVICE_NAME
      value: "cdtn-api"
    - name: ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME
      value: "true"
    - name: ELASTIC_APM_ENVIRONMENT
      value: "cdtn-${BRANCH_HASH}"
    - name: NLP_URL
      value: "${NLP_URL}"
    - name: NODE_ENV
      value: "production"
    - name: ELASTIC_APM_ACTIVE
      value: "$ENABLE_APM"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"
    - name: PIWIK_SITE_ID
      valueFrom:
        secretKeyRef:
          name: cdtn-secret
          key: PIWIK_SITE_ID
    - name: PIWIK_URL
      valueFrom:
        secretKeyRef:
          name: cdtn-secret
          key: PIWIK_URL

  initContainers:
    - name: wait-for-nlp
      image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/curl:1.53.1
      resources:
        requests:
          cpu: 5m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi
      command:
        - sh
        - -c
        - |
          retry=120; # 5s * (12 * 10) = 10min
          while
            ! wget -q -O - "$@" ${NLP_URL}/v1/models/sentqam &&
            [[ $(( retry-- )) -gt 0 ]];
          do echo "Waiting for api to respond ($(( retry )))" ; sleep 5s ; done ;

          [[ $(( retry )) -lt 1 ]] && exit 128;

          echo Ready;

service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: buypass
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: ${API_HOST}
      paths:
        - path: /
          servicePort: ${PORT}

  tls:
    - hosts:
        - ${API_HOST}
      secretName: api-crt

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUAverageUtilizationPercentage: 80
  targetMemoryAverageUtilizationPercentage: 80
