---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${CONTEXT}
  labels:
    app: ${CONTEXT}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  template:
    spec:
      containers:
        - image: ${IMAGE_NAME}:${IMAGE_TAG}
          name: ${CONTEXT}
          env:
            # - name: NODE_OPTIONS
            #   value: "--max_old_space_size=2048"
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-cloud-data
                  key: url
            - name: ELASTICSEARCH_DATA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-cloud-data
                  key: ELASTICSEARCH_DATA_TOKEN
            - name: ES_LOGS
              valueFrom:
                secretKeyRef:
                  name: monolog
                  key: ES_LOGS
            - name: ES_LOGS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: monolog
                  key: ES_LOGS_TOKEN
            - name: ES_INDEX_PREFIX
              value: "${ES_INDEX_PREFIX}"
            - name: NLP_URL
              value: "${NLP_URL}"
            - name: "CDTN_ADMIN_ENDPOINT"
              value: "${CDTN_ADMIN_ENDPOINT}"
          resources:
            requests:
              cpu: 1000m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 2Gi
      initContainers:
        - name: wait-for-nlp
          image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/curl:1.53.1
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
          command:
            - sh
            - -c
            - |
              echo "connecting to ${NLP_URL}/v1/models/sentqam";
              retry=60;
              while
                ! curl -sS "${NLP_URL}/v1/models/sentqam" &&
                [[ $(( retry-- )) -gt 0 ]];
              do echo "Waiting for nlp api to be ready ($retry)" ; sleep 5 ; done ;
              [[ $(( retry )) -lt 1 ]] && exit 1;

              echo Ready;

      restartPolicy: Never
