---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${CONTEXT}
  labels:
    app: ${CONTEXT}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  template:
    spec:
      containers:
        - image: ${IMAGE_NAME}:${IMAGE_TAG}
          name: ${CONTEXT}
          env:
            # - name: NODE_OPTIONS
            #   value: "--max_old_space_size=2048"
            - name: ELASTICSEARCH_URL
              value: "${CI_ELASTICSEARCH_CLUSTER}"
            - name: ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: user
            - name: ELASTICSEARCH_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: password
            - name: ES_INDEX_PREFIX
              value: "cdtn-${BRANCH_HASH}"
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 2Gi
      restartPolicy: Never
