
# dont include restore jobs on deploys
components = [
  "!ingester-elasticsearch",
  "!restore",
  "*"
]
require = ["ts-node/register"]

# dont include underscores-prefix components
[environments.prod]
components = ["!_*"]
