fullnameOverride: ${NLP_HOST}

image:
  repository: ${CI_REGISTRY_IMAGE}/nlp

deployment:
  port: ${PORT}

  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 2.5Gi

  livenessProbe:
    path: /
    failureThreshold: 2
    initialDelaySeconds: 40
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 3
  readinessProbe:
    path: /api/ready
    failureThreshold: 2
    initialDelaySeconds: 30
    periodSeconds: 2
    successThreshold: 1
    timeoutSeconds: 3

  env:
    - name: FLASK_APP
      value: "api"
    - name: NLP_PORT
      value: "${PORT}"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"

service:
  port: ${PORT}
  targetPort: ${PORT}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUAverageUtilizationPercentage: 80
