image:
  repository: ${CI_REGISTRY_IMAGE}/nlp
  tag: master

deployment:

  port: ${PORT}

  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1.9Gi

  readinessProbe:
    path: /api/ready
    initialDelaySeconds: 30
    periodSeconds: 10

  env:
    - name: FLASK_APP
      value: "api"
    - name: NLP_PORT
      value: "${PORT}"
    - name: SUGGEST_DATA_URL
      value: "${SUGGEST_DATA_URL}"
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${VERSION}"

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: nlp.code.travail.dev.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
        - nlp.code.travail.dev.fabrique.social.gouv.fr
      secretName: wildcard-crt
