apiVersion: v1
kind: Secret
metadata:
  name: cdtn-secret
data:
  IS_PRODUCTION_DEPLOYMENT: "ZmFsc2UK" # false
  SENTRY_PUBLIC_DSN: "aHR0cHM6Ly9jMmFhN2U3MzFhNDk0Y2ZkOGY3ZmIxZGRhYmNhMTFjOUBzZW50cnkuZmFicmlxdWUuc29jaWFsLmdvdXYuZnIvNQ==" # https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
  AZURE_BASE_URL: "aHR0cHM6Ly9jZHRuYWRtaW5kZXYuYmxvYi5jb3JlLndpbmRvd3MubmV0" # https://cdtnadmindev.blob.core.windows.net
type: Opaque
