---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v4.3.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v4.3.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v4.3.0
  #
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/manual.yml
  - /.gitlab-ci/stages/scan.yml
  - /.gitlab-ci/stages/deploy.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/update-fiches-mt.yml

  - /optional/e2e/.runners/puppetteer/.gitlab-ci.yml

stages:
  - "FichesMT"
  - "Prepare"
  - "Code Quality"
  - "Manual Deploy"
  - "Registration"
  - "Post Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  - E2E test
