---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_kosko_stage.yml
    ref: v20.7.11

  #
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/manual.yml
  - /.gitlab-ci/stages/scan.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/e2e.yml
  - /.gitlab-ci/stages/storage.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  # - "Update ES data"

#


.base_stage:
  rules:
    - if: $PRODUCTION
      when: never
    - if: $UPDATE_ES_INDEX
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^chore(release):*/
      when: never
    - when: always

k8s test:
  stage: Prepare
  needs: []
  extends:
    - .base_kosko_k8s_test
    - .base_stage

"@socialgouv/cdtn-logger":
  stage: Prepare
  extends:
    - .base_stage
  trigger:
    include:
      - local: /infra/logger/.gitlab-ci.yml
    strategy: depend

ingester:
  stage: Code Quality
  needs:
    - job: "@socialgouv/cdtn-logger"
  trigger:
    include:
      - local: /modules/ingester/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🚀 Review:
  extends:
    - .base_deploy_kosko_stage
  stage: Deploy
  rules:
    - if: "$PRODUCTION || $RELEASE || $CI_COMMIT_TAG"
      when: never
    - when: on_success
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  variables:
    KOSKO_GENERATE_ARGS: --env dev

🚀 Preprod:
  extends:
    - .base_deploy_kosko_stage
  stage: Deploy
  rules:
    - if: "$PRODUCTION || $RELEASE"
      when: never
    - if: "$CI_COMMIT_TAG"
  environment:
    name: preprod-dev2
    url: https://preprod-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  variables:
    KOSKO_GENERATE_ARGS: --env preprod

🚀 Production:
  extends:
    - .base_deploy_kosko_stage
  stage: Deploy
  rules:
    - if: "$PRODUCTION && $CI_COMMIT_TAG"
  environment:
    name: prod2
    url: https://${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  variables:
    KOSKO_GENERATE_ARGS: --env prod
