---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.1
  #
  # - /.gitlab-ci/variables.yml
  # - /.gitlab-ci/stages/quality.yml
  # - /.gitlab-ci/stages/register.yml
  # - /.gitlab-ci/stages/manual.yml
  # - /.gitlab-ci/stages/scan.yml
  # - /.gitlab-ci/stages/deploy.yml
  # - /.gitlab-ci/stages/notify.yml
  # - /.gitlab-ci/stages/e2e.yml

stages:
  # - "Prepare"
  # - "Code Quality"
  # - "Manual Deploy"
  # - "Registration"
  # - "Post Registration"
  # - "Deploy"
  # - "Notify Finished Deployment"
  # - "E2E testing"
  # - "Update ES data"
  - changes
  - tasks
changes:
  stage: changes
  image: alpine/git
  script:
    - sh scripts/changes.sh packages/code-du-travail-data packages/code-du-travail-api
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    untracked: true
    expire_in: 7 day
    paths:
      - .

skipped:
  stage: tasks
  before_script:
    - >-
      if [ -f CODE_DU_TRAVAIL_DATA_SKIP ]; then
        exit "${CI_JOB_SKIP_EXIT_CODE:-0}"
      fi
  script:
    - echo "register code-du-travail-data"

unskipped:
  stage: tasks
  before_script:
    - >-
      if [ -f CODE_DU_TRAVAIL_API_SKIP ]; then
        exit "${CI_JOB_SKIP_EXIT_CODE:-0}"
      fi
  script:
    - echo "register code-du-travail-api"
