---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_kosko_stage.yml
    ref: v20.7.14

  #

  - /.gitlab-ci/variables.yml
  # - /.gitlab-ci/stages/quality.yml
  # - /.gitlab-ci/stages/register.yml
  # - /.gitlab-ci/stages/manual.yml
  # - /.gitlab-ci/stages/scan.yml
  # - /.gitlab-ci/stages/deploy.yml
  # - /.gitlab-ci/stages/notify.yml
  # - /.gitlab-ci/stages/e2e.yml
  # - /.gitlab-ci/stages/storage.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  # - "Update ES data"

#

variables:
  MONOREPO_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/monorepo

.base_stage:
  rules:
    - if: $PRODUCTION
      when: never
    - if: $UPDATE_ES_INDEX
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^chore(release):*/
      when: never
    - when: always

🛂 k8s test:
  stage: Prepare
  needs: []
  extends:
    - .base_kosko_k8s_test
    - .base_stage

📦 logger:
  stage: Prepare
  extends:
    - .base_stage
  trigger:
    include:
      - local: /infra/logger/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    # MONOREPO_CACHE_FOLDER: $MONOREPO_CACHE_FOLDER

🧱 ingester:
  stage: Code Quality
  needs:
    - job: 📦 logger
  trigger:
    include:
      - local: /modules/ingester/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    # MONOREPO_CACHE_FOLDER: $MONOREPO_CACHE_FOLDER

🎯 ingester-elasticsearch:
  stage: Registration
  needs:
    - job: 📦 logger
    - job: 🧱 ingester
  trigger:
    include:
      - local: /targets/ingester-elasticsearch/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    # MONOREPO_CACHE_FOLDER: $MONOREPO_CACHE_FOLDER

🎯 api:
  stage: Registration
  needs:
    - job: 📦 logger
  trigger:
    include:
      - local: /packages/code-du-travail-api/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    # MONOREPO_CACHE_FOLDER: $MONOREPO_CACHE_FOLDER

🚀 ingester-elasticsearch (dev):
  stage: Deploy
  only:
    - branches
  extends:
    - .base_deploy_kosko_stage
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
  needs:
    - job: 🎯 ingester-elasticsearch
  variables:
    # kosko options
    KOSKO_GENERATE_ARGS: _namespace ingester-elasticsearch --env dev
    # jobs/injestor variables
    CDTN_ADMIN_ENDPOINT: https://cdtn-admin.fabrique.social.gouv.fr/api/graphql
    ES_INDEX_PREFIX: "cdtn-dev-${CI_COMMIT_REF_SLUG}"
