---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_kosko_stage.yml
    ref: v20.1.5
  #
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/manual.yml
  - /.gitlab-ci/stages/scan.yml
  - /.gitlab-ci/stages/deploy.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/e2e.yml
  - /.gitlab-ci/stages/storage.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Post Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  - "E2E testing"
  # - "Update ES data"
