---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v4.0.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v4.0.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v4.0.1
  #
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/02-quality.yml
  - /.gitlab-ci/stages/03-register.yml
  - /.gitlab-ci/stages/04-scan.yml
  - /.gitlab-ci/stages/06-deploy.yml
  - /.gitlab-ci/stages/07-notify.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Post Registration"
  - "Deploy"
  - "Notify Finished Deployment"
