---
include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/extends.yml
  - /.gitlab-ci/stages/prepare.yml
  - /.gitlab-ci/stages/quality.yml
  # - /.gitlab-ci/stages/register.yml
  # - /.gitlab-ci/stages/scan.yml
  # - /.gitlab-ci/stages/deploy.yml
  # - /.gitlab-ci/stages/notify.yml

stages:
  - "Prepare"
  - "Code Quality"
  # - "Registration"
  # - "Post Registration"
  # - "Vuln scanner"
  # - "Deploy"
  # - "Notify Finished Deployment"
