---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v5.0.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v5.0.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v5.0.0
  #
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/manual.yml
  - /.gitlab-ci/stages/scan.yml
  - /.gitlab-ci/stages/deploy.yml
  - /.gitlab-ci/stages/notify.yml

  - /packages/code-du-travail-nlp/.gitlab-ci.yml

  - /optional/e2e/.runners/puppetteer/.gitlab-ci.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Manual Deploy"
  - "Registration"
  - "Post Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  - E2E test

#

.base_stage:
  except:
    variables:
      # Don't run when tagging a commit
      - $RELEASE
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST

.prepare_stage:
  extends: .base_stage
  stage: "Prepare"
  dependencies: []
