#

include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/templates/docker.stage.yml
  #
  - /k8s/api/.deploy-api-to-k8s.yml
  - /k8s/data/.deploy-data-to-k8s.yml
  - /k8s/elasticsearch/.deploy-elasticsearch-k8s.yml
  - /k8s/frontend/.deploy-frontend-to-k8s.yml
  - /k8s/kibana/.deploy-kibana-to-k8s.yml
  #
  - /.gitlab-ci/stages/prepare.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/deploy.yml
  #


#

stages:
- "Prepare"
- "Code Quality"
- "Registration"
- "Deploy"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Notify Finished Deployment"
- "Delete Pods"
