---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_kosko_stage.yml
    ref: v20.7.11

  #

  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/manual.yml
  - /.gitlab-ci/stages/scan.yml
  - /.gitlab-ci/stages/deploy.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/e2e.yml
  - /.gitlab-ci/stages/storage.yml

  #

  - /infra/logger/.gitlab-ci.yml

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 3
  #
  MONOREPO_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/monorepo

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  # - "Update ES data"


.base_stage:
  dependencies: []
  rules:
    - if: $PRODUCTION
      when: never
    - if: $UPDATE_ES_INDEX
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^chore(release):*/
      when: never
    - when: always
