---
include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_helm_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_docker_kubectl_image_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_kosko_stage.yml
    ref: v20.7.14

  #

  - /.gitlab-ci/variables.yml
  # - /.gitlab-ci/stages/quality.yml
  # - /.gitlab-ci/stages/register.yml
  # - /.gitlab-ci/stages/manual.yml
  # - /.gitlab-ci/stages/scan.yml
  # - /.gitlab-ci/stages/deploy.yml
  # - /.gitlab-ci/stages/notify.yml
  # - /.gitlab-ci/stages/e2e.yml
  # - /.gitlab-ci/stages/storage.yml

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Deploy"
  - "Notify Finished Deployment"
  # - "Update ES data"

#

# variables:
  # MONOREPO_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/monorepo"

.base_stage:
  rules:
    - if: $PRODUCTION
      when: never
    - if: $UPDATE_ES_INDEX
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^chore(release):*/
      when: never
    - when: always

🛂 k8s test:
  extends:
    - .base_kosko_k8s_test
    - .base_stage
  stage: Prepare
  needs: []

📦 logger:
  extends:
    - .base_stage
  stage: Prepare
  needs: []
  trigger:
    include:
      - local: /infra/logger/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

📦 react-ui:
  extends:
    - .base_stage
  stage: Prepare
  needs: []
  trigger:
    include:
      - local: /packages/react-ui/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

📦 react-fiche-service-public:
  extends:
    - .base_stage
  stage: Code Quality
  needs:
    - job: 📦 react-ui
  trigger:
    include:
      - local: /packages/react-fiche-service-public/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🧱 ingester:
  extends:
    - .base_stage
  stage: Code Quality
  needs:
    - job: 📦 logger
  trigger:
    include:
      - local: /modules/ingester/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🎯 ingester-elasticsearch:
  extends:
    - .base_stage
  stage: Registration
  needs:
    - job: 🧱 ingester
  trigger:
    include:
      - local: /targets/ingester-elasticsearch/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🎯 www:
  extends:
    - .base_stage
  stage: Registration
  needs:
    - job: 📦 react-ui
  trigger:
    include:
      - local: /packages/code-du-travail-frontend/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🎯 api:
  extends:
    - .base_stage
  stage: Registration
  needs:
    - job: 📦 logger
  trigger:
    include:
      - local: /packages/code-du-travail-api/.gitlab-ci.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

🚀 ingester-elasticsearch (dev):
  extends:
    - .base_deploy_kosko_stage
  stage: Deploy
  rules:
    - if: "$PRODUCTION || $RELEASE || $CI_COMMIT_TAG"
      when: never
    - when: on_success
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
  needs:
    - job: 🛂 k8s test
    - job: 🎯 ingester-elasticsearch
  before_script:
    - kubectl config set-context --current --namespace=${KUBE_NAMESPACE}
    #
    # Do nothing if the job already exits
    # Exept if the job is triggered through the web interface.
    - |
      if kubectl get job ingester-elasticsearch; then
        if [[ $CI_PIPELINE_SOURCE == "web" ]]; then
          kubectl delete job ingester-elasticsearch || true
        else
          echo "Job found on ${CI_ENVIRONMENT_SLUG}"
          echo "Skip !"
          exit 0
        fi
      fi
  variables:
    # kosko options
    KOSKO_GENERATE_ARGS: _namespace ingester-elasticsearch --env dev
    # jobs/injestor variables
    CDTN_ADMIN_ENDPOINT: https://cdtn-admin.fabrique.social.gouv.fr/api/graphql

🚀 Review:
  extends:
    - .base_deploy_kosko_stage
  stage: Deploy
  rules:
    - if: "$PRODUCTION || $RELEASE || $CI_COMMIT_TAG"
      when: never
    - when: on_success
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  needs:
    - job: 🛂 k8s test
    - job: 🎯 api
    - job: 🎯 www
  variables:
    # kosko options
    KOSKO_GENERATE_ARGS: --env dev
    # jobs/injestor variables
    CDTN_ADMIN_ENDPOINT: https://cdtn-admin.fabrique.social.gouv.fr/api/graphql
