---
include:
- '/k8s/kibana/.deploy-kibana-k8s.yml'
- '/k8s/elasticsearch/.deploy-elasticsearch-k8s.yml'
- '/k8s/apm-server/.deploy-apm-server-k8s.yml'
- '/k8s/code-du-travail-data/.deploy-code-du-travail-data-k8s.yml'
- '/k8s/code-du-travail-api/.deploy-code-du-travail-api-k8s.yml'
- '/k8s/code-du-travail-frontend/.deploy-code-du-travail-frontend-k8s.yml'

variables:
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"

image: node:10-alpine

stages:
- "Install NPM Dependencies"
- "Build Assets"
- "Build & Push Docker Image"
- "Deploy EL Stack"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Deploy Code du Travail Numerique"

install-dependencies:
  stage: "Install NPM Dependencies"
  script:
  - yarn
  artifacts:
    expire_in: "1 day"
    paths:
    - node_modules
    - packages/code-du-travail-ui/node_modules
    - packages/code-du-travail-frontend/node_modules
    - packages/code-du-travail-css/node_modules
    - packages/code-du-travail-api/node_modules

build-api-assets:
  stage: "Build Assets"
  script:
  - yarn build
  artifacts:
    expire_in: "1 day"
    paths:
    - packages/code-du-travail-api/dist

build-and-push-elasticsearch-image:
  stage: "Build & Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - cd docker/elasticsearch
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  - docker build -t "$CI_REGISTRY_IMAGE/elasticsearch:latest" .
  - docker push "$CI_REGISTRY_IMAGE/elasticsearch:latest"

build-and-push-cdtn-api-image:
  stage: "Build & Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - cd packages/code-du-travail-api
  - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  - docker build -t "$CI_REGISTRY_IMAGE/api:latest" .
  - docker push "$CI_REGISTRY_IMAGE/api:latest"

build-and-push-cdtn-frontend-image:
  stage: "Build & Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - cd packages/code-du-travail-frontend
  - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  - docker build -t "$CI_REGISTRY_IMAGE/frontend:latest" .
  - docker push "$CI_REGISTRY_IMAGE/frontend:latest"

build-and-push-cdtn-data-image:
  stage: "Build & Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - cd packages/code-du-travail-data
  - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  - docker build -t "$CI_REGISTRY_IMAGE/data:latest" .
  - docker push "$CI_REGISTRY_IMAGE/data:latest"

deploy-kibana:
  stage: "Deploy EL Stack"
  extends: .deploy-kibana-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-elasticsearch:
  stage: "Deploy EL Stack"
  extends: .deploy-elasticsearch-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-apm-server:
  stage: "Deploy EL Stack"
  extends: .deploy-apm-server-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

create-cdtn-es-index:
  stage: "Create Code du Travail Numerique Elasticsearch Index"
  extends: .deploy-code-du-travail-data-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-cdtn-api:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-api-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-cdtn-frontend:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-frontend-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops
