---
include:
- '/k8s/kibana/.deploy-kibana-k8s.yml'
- '/k8s/elasticsearch/.deploy-elasticsearch-k8s.yml'
- '/k8s/apm-server/.deploy-apm-server-k8s.yml'
- '/k8s/code-du-travail-data/.deploy-code-du-travail-data-k8s.yml'
- '/k8s/code-du-travail-api/.deploy-code-du-travail-api-k8s.yml'
- '/k8s/code-du-travail-frontend/.deploy-code-du-travail-frontend-k8s.yml'

variables:
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"

image: node:10-alpine

stages:
- "Prepare"
- "Code Quality"
- "Build and Push Docker Image"
- "Deploy EL Stack"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Deploy Code du Travail Numerique"

prepare-cdtn-base-image:
  stage: "Prepare"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

prepare-env-file:
  stage: "Prepare"
  script:
  - node scripts/setup-env.js
  artifacts:
    paths:
    - .env

lint-cdtn-api:
  stage: "Code Quality"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - docker run -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" yarn workspace @cdt/api lint

lint-cdtn-ui:
  stage: "Code Quality"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - docker run -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" yarn workspace @cdt/ui lint

lint-cdtn-frontend:
  stage: "Code Quality"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - docker run -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" yarn workspace @cdt/frontend lint

lint-cdtn-data:
  stage: "Code Quality"
  image: python:3.6-alpine
  variables:
    DOCKER_HOST: tcp://localhost:2375
    PIPENV_VENV_IN_PROJECT: 1
    PIPENV_IGNORE_VIRTUALENVS: 1
  services:
  - docker:dind
  before_script:
  - cd packages/code-du-travail-data
  - apk add build-base
  - pip install --upgrade pip
  - pip install pipenv==11.10.1
  - pipenv install --dev --three
  script:
  - pipenv run pylint --output-format=colorized search

test-cdtn-frontend:
  stage: "Code Quality"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  script:
  - docker run -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" yarn workspace @cdt/frontend test --coverage

test-cdtn-api:
  stage: "Code Quality"
  image: docker/compose:1.23.2
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - docker-compose up -d elasticsearch
  - retry=0; while ! curl "http://localhost:9200/_cat/health?h=status" && (( $retry <= 60 )) ; do sleep 1; ((retry++)); done;
  - >-
    docker run
    -e ELASTICSEARCH_LOG_LEVEL=info
    -e ELASTICSEARCH_URL=http://elasticsearch:9200
    --network $(docker network ls -qf name=code)
    "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    node packages/code-du-travail-api/tests/create_indexes.js
  script:
  - >-
    docker run
    -e ELASTICSEARCH_URL=http://elasticsearch:9200
    -e ELASTICSEARCH_LOG_LEVEL=info
    --network $(docker network ls -qf name=code)
    "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    yarn workspace @cdt/api test --coverage

test-cdtn-data:
  stage: "Code Quality"
  image: python:3.6-alpine
  variables:
    DOCKER_HOST: tcp://localhost:2375
    PIPENV_VENV_IN_PROJECT: 1
    PIPENV_IGNORE_VIRTUALENVS: 1
    PYTHONPATH: .
  services:
  - docker:dind
  before_script:
  - cd packages/code-du-travail-data
  - apk add build-base
  - pip install --upgrade pip
  - pip install pipenv==11.10.1
  - pipenv install --dev
  script:
  - pipenv run python search/indexing/document_slug_checker.py -v

build-and-push-elasticsearch-image:
  stage: "Build and Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - cd docker/elasticsearch
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build -t "$CI_REGISTRY_IMAGE/elasticsearch:latest" .
  - docker push "$CI_REGISTRY_IMAGE/elasticsearch:latest"

build-and-push-cdtn-api-image:
  stage: "Build and Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - cd packages/code-du-travail-api
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA -t "$CI_REGISTRY_IMAGE/api:latest" .
  - docker push "$CI_REGISTRY_IMAGE/api:latest"

build-and-push-cdtn-frontend-image:
  stage: "Build and Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - cd packages/code-du-travail-frontend
  - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA -t "$CI_REGISTRY_IMAGE/frontend:latest" .
  - docker push "$CI_REGISTRY_IMAGE/frontend:latest"

build-and-push-cdtn-data-image:
  stage: "Build and Push Docker Image"
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - docker:dind
  before_script:
  - cd packages/code-du-travail-data
  - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
  - docker build -t "$CI_REGISTRY_IMAGE/data:latest" .
  - docker push "$CI_REGISTRY_IMAGE/data:latest"

deploy-kibana:
  stage: "Deploy EL Stack"
  extends: .deploy-kibana-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-elasticsearch:
  stage: "Deploy EL Stack"
  extends: .deploy-elasticsearch-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-apm-server:
  stage: "Deploy EL Stack"
  extends: .deploy-apm-server-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

create-cdtn-es-index:
  stage: "Create Code du Travail Numerique Elasticsearch Index"
  extends: .deploy-code-du-travail-data-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-cdtn-api:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-api-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops

deploy-cdtn-frontend:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-frontend-k8s
  variables:
    DOCKER_HOST: tcp://localhost:2375
    K8S_SERVER: $K8S_SERVER
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME
    K8S_NAMESPACE: $K8S_NAMESPACE
    K8S_USERNAME: $K8S_USERNAME
    K8S_CONTEXT: $K8S_CONTEXT
    K8S_TOKEN: $K8S_TOKEN
  environment:
    name: ops
