
Test Elastic 7.6.0:
  image: "curlimages/curl:7.67.0"
  services:
    - "docker.elastic.co/elasticsearch/elasticsearch:7.6.1"
  script:
    - curl localhost:9200/_cat/health?h=status
    - curl localhost:9200/_cat/nodes?v&pretty
