Test Elastic 7.6.0:
  image: "curlimages/curl:7.67.0"
  services:
    - name: "docker.elastic.co/elasticsearch/elasticsearch:7.6.0"
      alias: elasticsearch-yo
      command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
  variables:
    ELASTICSEARCH_URL: http://elasticsearch-yo:9200
  script:
    - |-
      echo $ELASTICSEARCH_URL;
      echo $CI_COMMIT_REF_SLUG;
      retry=3600;
      while
        ! curl "$ELASTICSEARCH_URL" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for Elasticsearch to go Green ($retry)" ; sleep 1 ; done ;
      [ "$retry" -eq "-1" ] && exit 1
