---
include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/stages/01-register-base.yml
  - /.gitlab-ci/stages/02-quality.yml
  - /.gitlab-ci/stages/03-register.yml
  - /.gitlab-ci/stages/04-scan.yml
  - /.gitlab-ci/stages/05-register-data.yml

  - /.gitlab-ci/stages/06-deploy.yml

  - /.gitlab-ci/stages/07-notify.yml


stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"

  - "Post Registration"
  - "Deploy"
  - "Notify Finished Deployment"
