dist: trusty
sudo: false
language: generic
git:
  depth: 5

#

_environments:
  - &docker_image
    - REPO_SLUG=$(echo $TRAVIS_REPO_SLUG | tr A-Z a-z)
    - DOCKER_IMAGE="$(echo $REPO_SLUG | tr A-Z a-z):${TRAVIS_COMMIT:0:7}"
  - &docker-keys
    - secure: "a7WHi3jik/AmtECoFH/5OfJ2+5RUN1sT5NDoH8pHosmkca4lrtwghokzbvYGgaLGSH8sBbvBkKXhNoGVh9wI2Vs4rvPVybfQH/VpG3iHD4IkHTSlGZYUTwz7/ih1ucssHkizEQ2zDTjjpQMTxcdldH+zxk1ECGrnfyctqXjugITYuBmafzDeHwPGtThslx0WE3MKiKs4HWrIfT6HcKhhTsQ4mqgXxcllnXLrx2l2BjsPYh8h5vxif7wM6f67h0Qzv7qXdSKkRQm3ETHDdQ1f4T2G+Xc1SsFPR6z7NyNPpBn76/qcZJ22lL6EKDdaAAs7Oqlr5MmBZbZDdvip8sWBM97cMT1jreqvbzctmt9dqkP/57fYfJjeinLLApKeNp35v+j3gCKRaDr695+JLqLfTu+DyNjaRhHZhfcVSJV1MwevJCfqOsdIR/2WJntfsoiCM35DW1QvA+2ommQU7WkDCrvj+btRBQc3i/bZA/I4tzP+x9NBC/z79LEMsrzQRvx71H1TNv5AKYvyfAIdRXhNLYa9yO+uzyO6nLesrpQBbPWOwGIMON3rSLgaXlim4KRgdNR1WTdXHhdlrDPmsU523Nx/2wgy3jvQ1ytTJIND+nmECnDdBOLuorjCWYxhzq3G8sjrz7qu3FF3tQnI19P4aQRfNONFGDG/yM5CzGph0Q8="
    - secure: "ei78PtEm9/OT1mt0h7T1tUXsdmDhfv0fW0umiFBuRWQ/dZo1GEnhIzhjW9AhVUY4597emNdr3MYcw0QUpyl2imRdFGcXsM7OHaq0Eh40qAjjwTVbCs1Rv7X3B39AYshOKHi/MrEiZ0lFVDALRH6kYEB/lmzCX1p7QuyPOyjPa4zB/9eZDxjJp22G/abBdZrqq2hnw9pBrcmxoHDDiXY8R+jIV15LQ4oXr/EJxNstgAffAflaTg/8QfnZzoXirSbdF6RfI4otIaJErALxnUdGJNkyCTrUJdsoFZ/LLg1B4QwRJfLwg3jLpkUyj+UOlCyk4zoFno8BMctlNFM29p/V1DPG4XihIcNDMVFbqdK0/9EXI6lAAdXv3OjOxGEKNeO/NTLCFLYQQgR2ezr9YV0SUPT8/fH6U2O8EzR4kPbOQ6QUwlISoQHhuKE/TwHTeYZ0k+AUg3YpZix6umYQBaC8iMGr+uAxMTldEAAOvrf1BF3fDBSbo72UTOQXUTaxBGSTDDxovZhKPJ5C7QgNbrUADAW1HDqyag1R5PCIIlveiHWZ2KbyfVOHtL/y5bA/qSWBrVxiIO9ZqUZzS5tHHBL+w1H0ZpwTPobScWsi58CoNT3p+noErRIaI4V4elgr188OLv9myTOnarRBblTAZuBihuNmU59p/gqEiykaFUpHez4="

#

jobs:
  include:
    - stage: Prepare
      name: Build and deploy current commit docker image
      env: [*docker_image, *docker-keys]
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_IMAGE .
        - docker images
        - docker push $DOCKER_IMAGE

    #
    #
    #

    - stage: Code quality
      name: Lint @cdt/frontend
      env: [*docker_image]
      script: docker run $DOCKER_IMAGE yarn workspace @cdt/frontend lint
    - #
      name: Lint @cdt/api
      env: [*docker_image]
      script: docker run $DOCKER_IMAGE yarn workspace @cdt/api lint
    - #
      name: Lint @cdt/ui
      env: [*docker_image]
      script: docker run $DOCKER_IMAGE yarn workspace @cdt/ui lint
    - #
      name: Test @cdt/ui
      env: [*docker_image]
      script: docker run $DOCKER_IMAGE yarn workspace @cdt/ui test
      after_success: npx codecov
    - #
      name: Test @cdt/frontend
      env: [*docker_image]
      script: docker run $DOCKER_IMAGE yarn workspace @cdt/frontend test
      after_success: npx codecov
    - #
      name: Lint python code
      language: python
      python: 3.6
      env:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
      cache: pip
      before_install: cd packages/code-du-travail-data
      install:
        - pip install --upgrade pip
        - pip install pipenv --upgrade
        - pipenv install --dev --three
      script: pipenv run pylint search

notifications:
  slack:
    secure: P9HLRFvTGbMuevLDkTKPnoI9PG4HhIt50I6kX5RCzADQUBS2tBhT7ENYm3YaPvjZNcMvD4K5LcVAmpBoQxI3ccsm+KPpit/MX52I8G3JpI0uKO/8vS7hZRtzeyAiM1ZnruKU02bQqN05wNZIB0wD4kL1zYusa5i9+Nq7TtUf4EziOfqP4cTmz13yQ6DWzph/0/x+Qxbui6dm/oBifqMfOiXdkOVlNiarjeIpyN0JYkNlEzuXdiqMwAiojMgr2JhXYScwfJKWQSwD8sjndOSAoFwF6LBSto2rxInNAYZx/+9oqy0cxxrxMQv19xAhSGi425HT1clLHUsDJelGOQEi8Kktk13WKjTaeOSynsjfLicPLUA8N6g5s7osUUAd0Tm4EoyH7UnVA8dm43QvhwPIIAMC+xcFhKfvc6BeR3asY+Lwyr4Mi3WAy0NfW2vInqmpWHGQxZt/tku/pldD7gtlXbwyx5q0j3bDBmsXkwvtfIkZIzfh6uW/xKPzRxjXxo0K4gttd89N4VhKEDw/9hzEuKTNIb5Wcvlfg53giNW6EBQX8jZGe8Br+YflwNddv8okl7lQbAeZGFaCGAxPzEM4ggIHZ9oYxo+44b/my0oqzI7nCaMfj18BlHdyygHef6rTDaGTeLgFbcMLK0mimO5X5+kgM4UdZvRZtrmfMv6onwo=
