version: "3"

services:
  elasticsearch:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  python:
    restart: "no"
    env_file:
      - .env
    depends_on:
      - elasticsearch


  nlp_api:
    restart: always
    env_file:
      - .env
    ports:
      - $NLP_PORT:$NLP_PORT


volumes:
  esdata:
    driver: local
