version: '3'

services:

  node:
    container_name: code-du-travail-explorer
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        NODE_ENV: $NODE_ENV
        API_URL: $API_URL
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./pages:/app/pages
      - ./routes.js:/app/routes.js
      - ./src:/app/src
      - ./static:/app/static
