version: "3"

services:
  elasticsearch:
    build:
      context: docker/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  python:
    env_file:
      - .env
    depends_on:
      - elasticsearch
    build:
      context: ./packages/code-du-travail-data
      dockerfile: ./Dockerfile

  nlp_api:
    env_file:
      - .env
    ports:
      - $NLP_PORT:$NLP_PORT
    build:
      context: ./packages/code-du-travail-nlp
      dockerfile: ./Dockerfile
    volumes:
      - ./packages/code-du-travail-nlp/data:/app/data

volumes:
  esdata:
    driver: local
