version: "3"

services:
  # In development, open ES port so host API can connect to it
  elasticsearch:
    ports:
      - 9200:9200

  python:
    volumes:
      - ./packages/code-du-travail-data/:/app
      - ./docker:/app/docker

  nlp_api:
    environment:
      - FLASK_ENV=development
    volumes:
      - ./packages/code-du-travail-nlp/:/app
    command: flask run --host=0.0.0.0
