version: "3"

services:
  # In production, dockerize the frontend
  frontend:
    image: socialgouv/code-du-travail-numerique-frontend:latest
    restart: always
    env_file:
      - .env
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT

  # In production, dockerize the API
  api:
    image: socialgouv/code-du-travail-numerique-api:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - elasticsearch
    environment:
      # defaults for production
      - APM_SERVER_URL=http://apm:8200
      - APM_SERVER_ACTIVE=1
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./packages/code-du-travail-data/dataset/courrier-type/docx:/code-du-travail-data/dataset/courrier-type/docx

  nlp_api:
    environment:
      - FLASK_ENV=production
