version: "3"

services:
  elasticsearch:
    build:
      context: ./docker/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  python:
    env_file:
      - .env
    depends_on:
      - elasticsearch
    build:
      context: ./packages/code-du-travail-data
      dockerfile: ./Dockerfile

  nlp_api:
    restart: always
    env_file:
      - .env
    ports:
      - $NLP_PORT:$NLP_PORT
    build:
      context: ./packages/code-du-travail-nlp
      dockerfile: ./Dockerfile

volumes:
  esdata:
    driver: local
