version: "3"

services:
  elasticsearch:
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  data:
    restart: "no"
    env_file:
      - .env
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
