version: '3'

services:

  # In production, dockerize the frontend
  frontend:
    restart: always
    env_file:
      - ./packages/code-du-travail-frontend/.env
      - .env
    build:
      context: ./packages/code-du-travail-frontend
      dockerfile: ./Dockerfile
      args:
        API_URL: $API_URL
        SENTRY_PUBLIC_DSN: $SENTRY_PUBLIC_DSN
        PIWIK_URL: $PIWIK_URL
        PIWIK_SITE_ID: $PIWIK_SITE_ID
    environment:
      - PORT=4000
      - API_URL=http://127.0.0.1:3005/api/v1
    ports:
      - 3004:4000

  # In production, dockerize the API
  api:
    restart: always
    env_file: ./packages/code-du-travail-api/.env
    depends_on:
      - elasticsearch
    build:
      context: ./packages/code-du-travail-api
      dockerfile: ./Dockerfile
    environment:
      - PORT=5000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - APM_SERVER_URL=http://apm:8200
      - APM_SERVER_ACTIVE=1
    ports:
      - 3005:5000

  # In production, add an APM Server
  apm:
    image: docker.elastic.co/apm/apm-server:6.2.4
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - logging.level=trace
      - setup.kibana.host=kibana:5601
      - apm-server.host=0.0.0.0:8200
      - output.elasticsearch.hosts=elasticsearch:9200
      - output.elasticsearch.enabled=true

  # In production, add kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
