version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./docker:/app/docker
    command:
      - sh
      - -c
      - "cp /app/docker/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml; ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu; docker-entrypoint.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  python:
    env_file:
      - .env
    depends_on:
      - elasticsearch
    build:
      context: ./packages/code-du-travail-data
      dockerfile: ./Dockerfile

  nlp_api:
    ports:
      - 5000:5000
    build:
      context: ./packages/code-du-travail-nlp
      dockerfile: ./Dockerfile

volumes:
  esdata:
    driver: local
