#
#
#

variables:
  CACHE_FALLBACK_KEY: logger-${CI_JOB_NAME}-${CI_DEFAULT_BRANCH}
  MONOREPO_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/monorepo

before_script:
  - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
  - sh ./.gitlab-ci/monorepo.sh skip && exit 0 || true
  - cd infra/elasticsearch

Install:
  stage: build
  image: node:14.16-alpine3.13
  needs: []
  cache:
    key:
      files:
        - yarn.lock
      prefix: logger-${CI_JOB_NAME}
    paths:
      - .cache
      - infra/elasticsearch/node_modules
      - node_modules
  before_script:
    - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
    - sh ./.gitlab-ci/monorepo.sh has-changed
        --find-ignore "*/node_modules/*"
        --verbose
        infra/elasticsearch || true
    - |
      sh ./.gitlab-ci/monorepo.sh skip && {
        rm -rf .cache/yarn infra/elasticsearch/node_modules node_modules;
        exit 0;
      } || true
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install --cwd infra/elasticsearch
    - yarn exec yarn-workspace-focus-install -- --cwd infra/elasticsearch
  artifacts:
    expire_in: 1 week
    paths:
      - ${MONOREPO_CACHE_FOLDER}/skip
      - infra/elasticsearch/node_modules
      - node_modules

#
#
#

Build:
  stage: test
  image: node:14.16-alpine3.13
  cache:
    key:
      files:
        - yarn.lock
      prefix: logger-${CI_JOB_NAME}
    paths:
      - infra/elasticsearch/lib
  variables:
    CI_DEBUG_TRACE: "true"
  needs:
    - job: Install
      artifacts: true
  script:
    # NOTE(douglasduteil): ensure to have clean build
    - rm -rf lib
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - infra/elasticsearch/lib

#
#
#

Lint:
  stage: test
  image: node:14.16-alpine3.13
  needs:
    - job: Install
      artifacts: true
  script:
    - yarn lint

#
#
#

Test:
  stage: test
  image: node:14.16-alpine3.13
  needs:
    - job: Install
      artifacts: true
  script:
    - yarn test
