#

Build data:
  stage: Prepare
  dependencies: []
  image: node:12.14-alpine3.10
  interruptible: true
  variables:
    CONTEXT: code-du-travail-data
  script:
    - "[[ type jq ]] || apk add jq=~1"

    # HACK(douglasduteil): remove all packages dependencies
    # To make the installation blazing fast, we remove all packages dependencies
    # Only the root package.json dependencies will be installed
    - find packages -maxdepth 1
      -not -name ${CONTEXT}
      -not -name sources
      -type d | tail -n +2 |
      xargs -I {} rm -rf {}

    # HACK(douglasduteil): remove all packages dependencies
    # To make the installation blazing fast, we remove all packages dependencies
    # Only the root package.json dependencies will be installed
    - find packages -maxdepth 1 -type d -not -name ${CONTEXT} | tail -n +2 |
      xargs -I {} sh -c "[[ -f "{}/package.json" ]] || exit 0 ; {
      rm {}/package.json ;
      jq 'del(.dependencies) | del(.devDependencies)' > {}/package.json
      ; } < {}/package.json"

    - find packages/${CONTEXT}/dataset -maxdepth 1 -type d | tail -n +2 |
      xargs -I {} sh -c "[[ -f "{}/package.json" ]] || exit 0 ; {
      rm {}/package.json ;
      jq 'del(.dependencies) | del(.devDependencies)' > {}/package.json
      ; } < {}/package.json"

    # NOTE(dougladuteil): remove dependencies and devDependencies
    # As we only install one package, we do not need the cross packages dependencies
    # like lerna or husky...
    - "{ rm package.json; jq 'del(.dependencies) | del(.devDependencies)' > package.json; } < package.json"

    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - yarn --frozen-lockfile --prefer-offline
    #
    # - yarn workspace @cdt/data dump-dev
  artifacts:
    expire_in: 1 day
    paths:
      - packages/${CONTEXT}/code-du-travail-data/dist
