#

Build data:
  stage: Prepare
  dependencies: []
  image: node:12.14-alpine3.10
  interruptible: true
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/.cache
  variables:
    CONTEXT: code-du-travail-data
    WORKSPACE: "@cdt/data"
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - npx @socialgouv/yarn-workspace-focus-install --cwd packages/${CONTEXT} --
      --frozen-lockfile --prefer-offline
    #
    - yarn workspace @cdt/data lint
    - yarn workspace @cdt/data build
  after_script:
    # HACK(douglasduteil): remove huge packages from cache
    # To allow less than a minute download/upload caching we remove our biggest
    # packages :
    # $ npm info @socialgouv/kali-data #.unpackedSize: ~380Mo
    - yarn cache clean @socialgouv/fiches-vdd
    # $ npm info @socialgouv/kali-data #.unpackedSize: ~390Mo
    - yarn cache clean @socialgouv/kali-data
    # $ npm info @socialgouv/legi-data #.unpackedSize: ~145Mo
    - yarn cache clean @socialgouv/legi-data
  artifacts:
    expire_in: 1 day
    paths:
      - packages/${CONTEXT}/code-du-travail-data/dist
