variables:
  PROJECT: cdtn
  APM_SERVER_PORT: 8200
  DOCKER_COMPOSE_VERSION: "1.23.2"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: 18
  ELASTICSEARCH_INTER_NODE_PORT: 9300
  ELASTICSEARCH_PORT: 9200
  FRONTEND_PORT: 3000
  GIT_STRATEGY: fetch
  HASH_SIZE: 7
  IMAGE_INFRA_BASE_NAME: infra/images-docker
  KIBANA_PORT: 5601
  NLP_URL: https://preprod-serving-ml.dev2.fabrique.social.gouv.fr
  CDTN_ADMIN_ENDPOINT: https://restore-db-featur-ylqd9w-cdtn-admin.dev2.fabrique.social.gouv.fr/api/graphql
  PYTHON_VERSION: 3.7.2-alpine
  RANCHER_PROJECT_ID: c-kk8xm:p-8q2jj
