---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-api${HASH_BRANCH_NAME}
  labels:
    app: cdtn-api${HASH_BRANCH_NAME}
    branch: ${BRANCH_NAME}
    commit: ${COMMIT}
    job: "${JOB_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-api${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-api${HASH_BRANCH_NAME}
    spec:
      containers:
      - image:  ${CDTN_REGISTRY}/api:${IMAGE_TAG}
        name: cdtn-api${HASH_BRANCH_NAME}
        ports:
        - containerPort: ${PORT}
        livenessProbe:
          httpGet:
            path: /api/v1/version
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/version
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: API_PORT
          value: "1337"
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch${HASH_BRANCH_NAME}:${ES_PORT}
        - name: ELASTICSEARCH_LOG_LEVEL
          value: "${ELASTICSEARCH_LOG_LEVEL}"
        - name: APM_SERVER_ACTIVE
          value: "${APM_SERVER_ACTIVE}"
        - name: APM_SERVER_URL
          value: "${APM_SERVER_URL}"
