.deploy-code-du-travail-nlp-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - export HASH_BRANCH_NAME=-$BRANCH_HASH
  #
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-nlp/deployment-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/deployment-cdtn-nlp.yml
  - envsubst < k8s/code-du-travail-nlp/service-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/service-cdtn-nlp.yml
  - envsubst < k8s/code-du-travail-nlp/ingress-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/ingress-cdtn-nlp.yml
  #
  - kubectl apply -f k8s/code-du-travail-nlp/deployment-cdtn-nlp.yml
  - kubectl apply -f k8s/code-du-travail-nlp/service-cdtn-nlp.yml
  - kubectl apply -f k8s/code-du-travail-nlp/ingress-cdtn-nlp.yml
  - echo "CDTN nlp available at - ${NLP_HOST}"
  allow_failure: false

.deploy-code-du-travail-nlp-prod-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-nlp/deployment-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/deployment-cdtn-nlp.yml
  - envsubst < k8s/code-du-travail-nlp/service-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/service-cdtn-nlp.yml
  - envsubst < k8s/code-du-travail-nlp/ingress-code-du-travail-nlp.yml > k8s/code-du-travail-nlp/ingress-cdtn-nlp.yml
  #
  - kubectl apply -f k8s/code-du-travail-nlp/deployment-cdtn-nlp.yml
  - kubectl apply -f k8s/code-du-travail-nlp/service-cdtn-nlp.yml
  - kubectl apply -f k8s/code-du-travail-nlp/ingress-cdtn-nlp.yml
  - echo "CDTN nlp available at - ${NLP_HOST}"
  allow_failure: false
