---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-nlp${HASH_BRANCH_NAME}
  labels:
    app: cdtn-nlp${HASH_BRANCH_NAME}
    branch: cdtn${HASH_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-nlp${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-nlp${HASH_BRANCH_NAME}
    spec:
      containers:
      - image:  ${CDTN_REGISTRY}/nlp:${IMAGE_TAG}
        name: cdtn-nlp${HASH_BRANCH_NAME}
        ports:
        - containerPort: ${PORT}
        livenessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: NLP_PORT
          value: "${PORT}"
        - name: FLASK_APP
          value: "api"
        - name: SUGGEST_DATA_URL
          value: "${SUGGEST_DATA}"
