---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-frontend${HASH_BRANCH_NAME}
  labels:
    app: cdtn-frontend${HASH_BRANCH_NAME}
    branch: ${BRANCH_NAME}
    commit: ${COMMIT}
    job: "${JOB_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-frontend${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-frontend${HASH_BRANCH_NAME}
    spec:
      containers:
      - image:  ${CDTN_REGISTRY}/frontend:${IMAGE_TAG}
        name: cdtn-frontend
        ports:
        - containerPort: ${PORT}
        livenessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: API_URL
          value: http://${API_HOST}
        - name: SUGGEST_URL
          value: http://${HASH_BRANCH_INGRESS}code-du-travail-numerique-nlp.${ENVIRONMENT}.factory.social.gouv.fr/api/suggest

