---

version: 2

#

workflows:
  version: 2
  do-the-thing:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
            - build

#

_job: &_job
  docker:
    - image: circleci/node:10
  working_directory: ~/repo

_restore_cache: &_restore_cache
  name: Restore Yarn Package Cache
  keys:
    - yarn-packages-{{ checksum "yarn.lock" }}

_save_cache: &_save_cache
  name: Save Yarn Package Cache
  key: yarn-packages-{{ checksum "yarn.lock" }}
  paths:
    - ~/.cache/yarn

_install: &_install
  yarn --frozen-lockfile

_setup: &_setup
  <<: *_job


#

jobs:
  install:
    <<: *_setup
    steps:
      - checkout
      - restore_cache: *_restore_cache
      - run: *_install
      - save_cache: *_save_cache
  build:
    <<: *_setup
    steps:
      - checkout
      - restore_cache:  *_restore_cache
      - run: *_install
      - save_cache: *_save_cache
      - run: yarn lerna run --stream build
  lint:
    <<: *_setup
    steps:
      - checkout
      - restore_cache:  *_restore_cache
      - run: *_install
      - save_cache: *_save_cache
      - run: yarn lerna run --stream lint
  test:
    <<: *_setup
    steps:
      - checkout
      - restore_cache:  *_restore_cache
      - run: *_install
      - save_cache: *_save_cache
      - run: yarn lerna run --stream test

