.deploy-code-du-travail-api-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - export HASH_BRANCH_NAME=-$BRANCH_HASH
  #
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-api/deployment-code-du-travail-api.yml > k8s/code-du-travail-api/deployment-cdtn-api.yml
  - envsubst < k8s/code-du-travail-api/service-code-du-travail-api.yml > k8s/code-du-travail-api/service-cdtn-api.yml
  - envsubst < k8s/code-du-travail-api/ingress-code-du-travail-api.yml > k8s/code-du-travail-api/ingress-cdtn-api.yml
  #
  - kubectl apply -f k8s/code-du-travail-api/deployment-cdtn-api.yml
  - kubectl apply -f k8s/code-du-travail-api/service-cdtn-api.yml
  - kubectl apply -f k8s/code-du-travail-api/ingress-cdtn-api.yml
  - echo "CDTN api available at - http://${API_HOST}"
  allow_failure: false

.deploy-code-du-travail-api-prod-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-api/deployment-code-du-travail-api.yml > k8s/code-du-travail-api/deployment-cdtn-api.yml
  - envsubst < k8s/code-du-travail-api/service-code-du-travail-api.yml > k8s/code-du-travail-api/service-cdtn-api.yml
  - envsubst < k8s/code-du-travail-api/ingress-code-du-travail-api.yml > k8s/code-du-travail-api/ingress-cdtn-api.yml
  #
  - kubectl apply -f k8s/code-du-travail-api/deployment-cdtn-api.yml
  - kubectl apply -f k8s/code-du-travail-api/service-cdtn-api.yml
  - kubectl apply -f k8s/code-du-travail-api/ingress-cdtn-api.yml
  - echo "CDTN api available at - http://${API_HOST}"
  allow_failure: false
