#

Snyk docker scan:
  stage: "Deploy"
  image: snyk/snyk-cli:docker
  services:
    - docker:$DOCKER_VERSION-dind
  except:
    variables:
      - $PRODUCTION
  dependencies: []
  needs:
    - Register api image
    - Register frontend image
    - Register nlp image
    - Register data image
  allow_failure: true
  before_script:
    - source .gitlab-ci/env.sh
  script:
    - ./scripts/snyk-docker-scan.sh

