#

include:
- project: SocialGouv/gitlab-ci-yml
  file: /base_notify_github_stage.yml
  ref: master

Notify Starting Deployment:
  extends: .base_notify_pending_stage
  stage: Deploy

Notify Fail:
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment

Notify Success:
  extends: .base_notify_success_stage
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment
#.notify_stage: &notify_stage
#  image: python:$PYTHON_VERSION
#  variables:
#    DEPLOY_ID_FILE: github_deploy_id
#  before_script:
#    - apk add --no-cache curl=7.64.0-r3
#    - source .gitlab-ci/env.sh
#  dependencies: []
#
##
##
##
#
# Release:
#   stage: "Notify Finished Deployment"
#   image: node:12.14-alpine3.10
#   only:
#     - master
#   when: manual
#   before_script:
#     - apk add --no-cache git=~2
#     - git checkout ${CI_COMMIT_REF_NAME}
#     - git config user.name "${CI_GIT_AUTHOR_NAME}"
#     - git config user.email "${CI_GIT_AUTHOR_EMAIL}"
#     - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
#     - yarn --frozen-lockfile
#   script:
#     - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}
#
##
##
##
#
#Production:
#  <<: *notify_stage
#  stage: "Notify Finished Deployment"
#  when: manual
#  only:
#    - tags
#  except:
#    variables:
#      - $PRODUCTION
#  script:
#    - echo "Put ${CI_COMMIT_REF_NAME}@${CI_COMMIT_SHORT_SHA} in production"
#    - curl --request POST
#      --form ref="${CI_COMMIT_REF_NAME}"
#      --form token="${CI_DEPLOY_TRIGGER}"
#      --form variables[PRODUCTION]="true"
#      https://gitlab.factory.social.gouv.fr/api/v4/projects/51/trigger/pipeline
