#

Register data image:
  extends: .base_register_stage
  stage: "Registration"
  except:
    variables:
      - $PRODUCTION
  services:
    - node:10-alpine
  cache:
    <<: *cache_template
    policy: pull
  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data

  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - yarn --frozen-lockfile
  script:
    - yarn workspace @cdt/data build
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=$CI_COMMIT_REF_SLUG
      fi
    #
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $IMAGE_NAME:$TAG || true
    - docker pull $IMAGE_NAME:master || true
    - echo "> docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG --cache-from $IMAGE_NAME:master -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:$TAG $CONTEXT"
    - docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG --cache-from $IMAGE_NAME:master -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:$TAG $CONTEXT
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$TAG
