#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_create_namespace_stage.yml
    ref: v4.0.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_nodejs_chart_stage.yml
    ref: v4.0.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_hpa_chart_stage.yml
    ref: v4.0.1

#

Create namespace:
  extends: .base_create_namespace_stage
  stage: "Post Registration"
  before_script:
    - source ./.gitlab-ci/env.sh
  after_script:
    - source ./.gitlab-ci/env.sh
    #
    # Create cdtn secrets
    - envsubst < ./.k8s/secrets.yml | kubectl apply -n ${K8S_NAMESPACE} -f - || true
    #
    # Copy elasticsearch-creds
    - kubectl get secret elasticsearch-cloud-data --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elasticsearch-cloud-api --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elastic-apm --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -

#

.deploy_stage: &deploy_stage
  stage: "Deploy"
  dependencies: []
  services:
    - docker:dind
  variables: &deploy_stage_variables
    IMAGE_TAG: ${CI_COMMIT_SHA}
    REGISTRY: ${CI_REGISTRY_IMAGE}

.incubateur_stage: &incubateur_stage
  environment:
    name: prod
  only:
    refs:
      - triggers
    variables:
      - $PRODUCTION

#

.dev_stage: &dev_stage
  environment: fabrique-dev

#
#
#

.deploy_api_stage: &deploy_api_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    CONTEXT: api
    PORT: 8000
    VALUES_FILE: ./.k8s/api.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${API_HOST}

#

Deploy @cdtn/api (dev):
  <<: *deploy_api_stage
  <<: *dev_stage

Deploy @cdtn/api (incubateur):
  <<: *deploy_api_stage
  <<: *incubateur_stage

#
#
#

.deploy_frontend_stage: &deploy_frontend_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONTEND_PORT}
    CONTEXT: frontend
    VALUES_FILE: ./.k8s/frontend.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_HOST}

#

Deploy @cdtn/frontend (dev):
  <<: *deploy_frontend_stage
  <<: *dev_stage

Deploy @cdtn/frontend (incubateur):
  <<: *deploy_frontend_stage
  <<: *incubateur_stage

#
#
#

.deploy-data: &deploy_data
  <<: *deploy_stage
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.20.0
  variables:
    <<: *deploy_stage_variables
    CONTEXT: data
    ES_PORT: ${ELASTICSEARCH_PORT}
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/data
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    - kubectl delete job ${CONTEXT} || true
    - cat ./.k8s/data.job.yml | envsubst | kubectl apply -f -

#

Create Elasticsearch Index (dev):
  <<: *deploy_data
  <<: *dev_stage

Create Elasticsearch Index (incubateur):
  <<: *deploy_data
  <<: *incubateur_stage

#
#
#

.deploy_nlp_stage: &deploy_nlp_stage
  <<: *deploy_stage
  extends: .base_deploy_nodejs_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${NLP_PORT}
    CONTEXT: nlp
    VALUES_FILE: ./.k8s/nlp.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${NLP_HOST}

#

Deploy @cdtn/nlp (dev):
  <<: *deploy_nlp_stage
  <<: *dev_stage

Deploy @cdtn/nlp (incubateur):
  <<: *deploy_nlp_stage
  <<: *incubateur_stage
