#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_create_namespace_stage.yml
    ref: v4.6.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_nodejs_chart_stage.yml
    ref: v4.6.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_hpa_chart_stage.yml
    ref: v4.6.0


#

.deploy_stage: &deploy_stage
  stage: "Deploy"
  except:
    variables:
      # Don't run when running e2e tests
      - $E2E_TEST
  dependencies: []
  services:
    - docker:dind
  variables: &deploy_stage_variables
    IMAGE_TAG: ${CI_COMMIT_SHA}
    REGISTRY: ${CI_REGISTRY_IMAGE}

.prod_stage: &prod_stage
  environment:
    name: prod
  only:
    variables:
      - $PRODUCTION

#

.dev_stage: &dev_stage
  environment:
    name: fabrique-dev
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/
#
#
#

.deploy_api_stage: &deploy_api_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    CONTEXT: api
    PORT: 8000
    VALUES_FILE: ./.k8s/api.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${API_HOST}

#

Deploy @cdtn/api (dev):
  <<: *deploy_api_stage
  <<: *dev_stage

Deploy @cdtn/api (prod):
  <<: *deploy_api_stage
  <<: *prod_stage

#
#
#

.deploy_frontend_stage: &deploy_frontend_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONTEND_PORT}
    CONTEXT: frontend
    VALUES_FILE: ./.k8s/frontend.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_HOST}

#

Deploy @cdtn/frontend (dev):
  <<: *deploy_frontend_stage
  <<: *dev_stage

Deploy @cdtn/frontend (prod):
  <<: *deploy_frontend_stage
  <<: *prod_stage

Deploy @cdtn/frontend extra ingress(prod):
  <<: *deploy_stage
  <<: *prod_stage
  extends: .base_docker_kubectl_image_stage
  script:
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - cat ./.k8s/ingress-prod.yml | envsubst | kubectl apply -f -
  before_script:
    - source ./.gitlab-ci/env.sh

#
#
#

.deploy-data: &deploy_data
  <<: *deploy_stage
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.20.0
  variables:
    <<: *deploy_stage_variables
    CONTEXT: data
    ES_PORT: ${ELASTICSEARCH_PORT}
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/data
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    - kubectl delete job ${CONTEXT} || true
    - cat ./.k8s/data.job.yml | envsubst | kubectl apply -f -

#

Create Elasticsearch Index (dev):
  <<: *deploy_data
  <<: *dev_stage

Create Elasticsearch Index (prod):
  <<: *deploy_data
  <<: *prod_stage

#
#
#

.deploy_nlp_stage: &deploy_nlp_stage
  <<: *deploy_stage
  extends: .base_deploy_nodejs_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${NLP_PORT}
    CONTEXT: nlp
    VALUES_FILE: ./.k8s/nlp.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${NLP_HOST}

#

Deploy @cdtn/nlp (dev):
  <<: *deploy_nlp_stage
  <<: *dev_stage

Deploy @cdtn/nlp (prod):
  <<: *deploy_nlp_stage
  <<: *prod_stage
