Test on deployed branch:
  stage: E2E testing
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/puppeteer:0.29.0
  except:
    refs:
      # Don't run on release
      - tags
    variables:
      # Don't run when deploying in production
      - $PRODUCTION

  environment:
    name: ${CI_COMMIT_REF_NAME}-dev2
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - optional/e2e/runners/puppeteer/node_modules
      - $CI_PROJECT_DIR/.yarn
  retry: 2

  before_script:
    - source ./.gitlab-ci/env.sh
    - CODECEPT_BASEURL=${FRONTEND_URL}
    - cd ./optional/e2e/runners/puppeteer
    - |-
      retry=60;
      while
        ! wget -q -O - "$@" "${FRONTEND_URL}/api/version"  | grep "${COMMIT}" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for frontend to be ready" ; sleep 3 ; done ;
      [ "$retry" -eq "-1" ] && exit 1

  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
    #
    - echo "${CODECEPT_BASEURL}"
    #
    - CODECEPT_BASEURL=${CODECEPT_BASEURL} yarn test
