#
#
#

Release:
  stage: "Deploy"
  image: node:12.14-alpine3.10
  dependencies: []
  when: manual
  before_script:
    - apk add --no-cache git=~2
    - git checkout ${CI_COMMIT_REF_NAME}
    - git config user.name "${CI_GIT_AUTHOR_NAME}"
    - git config user.email "${CI_GIT_AUTHOR_EMAIL}"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - yarn --frozen-lockfile
  script:
    - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}

#
#
#

Production:
  stage: "Deploy"
  image: curlimages/curl:7.67.0
  dependencies: []
  when: manual
  only:
    refs:
      - tags
  except:
    variables:
      - $PRODUCTION
  script:
    - curl --request POST
      --form ref="${CI_COMMIT_REF_NAME}"
      --form token="${CI_JOB_TOKEN}"
      --form variables[PRODUCTION]="true"
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline
