#
#
#

Release:
  stage: "Deploy"
  image: node:12.14-alpine3.10
  dependencies: []
  when: manual
  variables:
    LERNA_ARGS: --force-publish --yes --conventional-graduate
  except:
    refs:
      # Don't tag tags
      - tags
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
  before_script:
    - npm config set access public
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - apk add --no-cache git=~2
    - git checkout ${CI_COMMIT_REF_SLUG}
    - git config user.name "${CI_GIT_AUTHOR_NAME}"
    - git config user.email "${CI_GIT_AUTHOR_EMAIL}"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - yarn --frozen-lockfile
  script:
    - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}
    - yarn lerna publish from-package --yes

#
#
#

Production:
  stage: "Deploy"
  image: curlimages/curl:7.67.0
  dependencies: []
  when: manual
  only:
    refs:
      - tags
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/
  script:
    - curl --request POST
      --form ref="${CI_COMMIT_REF_SLUG}"
      --form token="${CI_JOB_TOKEN}"
      --form variables[PRODUCTION]="true"
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline

Preview:
  stage: "Prepare"
  image:  node:12.14-alpine3.10
  dependencies: []
  when: manual
  environment:
    name: preview-dev2
  variables:
    ES_INDEX_PREFIX: cdtn-preprod
    ELASTICSEARCH_USER: $ELASTICSEARCH_USER
    ELASTICSEARCH_PWD: $ELASTICSEARCH_PWD
    ELASTICSEARCH_PWD_2: "$ELASTICSEARCH_PWD"
    ELASTICSEARCH_PWD_3: '$ELASTICSEARCH_PWD'
    ELASTICSEARCH_PWD_4: "${ELASTICSEARCH_PWD}"
    ELASTICSEARCH_PWD_5: '${ELASTICSEARCH_PWD}'
    ELASTICSEARCH_URL: $ELASTICSEARCH_URL
    ES_LOGS: $ES_LOGS
    ES_LOGS_TOKEN: $ES_LOGS_TOKEN
    NLP_URL: $NLP_URL
    CDTN_ADMIN_ENDPOINT: https://lionelb-feat-docu-x5f3qv-cdtn-admin.dev2.fabrique.social.gouv.fr/api/graphql
  before_script:
    - echo ELASTICSEARCH_PWD
    - echo ELASTICSEARCH_PWD2
    - echo ELASTICSEARCH_PWD3
    - echo ELASTICSEARCH_PWD4
    - echo ELASTICSEARCH_PWD5
  script:
    - yarn workspace @cdt/data ingest
