#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_notify_github_stage.yml
    ref: v4.0.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_delete_useless_k8s_ns_stage.yml
    ref: v4.0.1
#

.notify_dev: &notify_dev
  only:
    - external_pull_request

.notify_prod: &notify_prod
  only:
    - $PRODUCTION

Notify Starting Dev Deployment:
  extends: .base_notify_pending_stage
  stage: Deploy
  <<: *notify_dev

Notify Starting Prod Deployment:
  extends: .base_notify_pending_stage
  stage: Deploy
  <<: *notify_prod

Notify Fail Dev:
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  <<: *notify_dev
  dependencies:
    - Notify Starting Dev Deployment

Notify Fail Prod:
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  <<: *notify_prod
  dependencies:
    - Notify Starting Prod Deployment

Notify Success Dev:
  extends: .base_notify_success_stage
  stage: Notify Finished Deployment
  <<: *notify_dev
  dependencies:
    - Notify Starting Dev Deployment

Notify Success Prod:
  extends: .base_notify_success_stage
  stage: Notify Finished Deployment
  <<: *notify_prod
  dependencies:
    - Notify Starting Prod Deployment

Delete useless k8s namespaces:
  extends: .base_delete_useless_k8s_ns_stage
