#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_notify_github_stage.yml
    ref: v4.3.0
  - project: SocialGouv/gitlab-ci-yml
    file: /base_delete_useless_k8s_ns_stage.yml
    ref: v4.3.0
#

Notify Starting Deployment:
  extends: .base_notify_pending_stage
  stage: Deploy
  except:
    - /^renovate/*

Notify Fail:
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  except:
    - /^renovate/*
  dependencies:
    - Notify Starting Deployment
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_URL}

Notify Success:
  extends: .base_notify_success_stage
  stage: Notify Finished Deployment
  except:
    - /^renovate/*
  dependencies:
    - Notify Starting Deployment
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_URL}

Delete useless k8s namespaces:
  extends: .base_delete_useless_k8s_ns_stage
