#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_notify_github_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_delete_useless_k8s_ns_stage.yml
    ref: v15.0.0

#

.notify_stage:
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_URL}

#

.notify_dev:
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev2
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

.notify_prod:
  environment:
    name: prod
  only:
    variables:
      - $PRODUCTION

#

Notify Starting Deployment:
  extends:
    - .base_notify_pending_stage
    - .notify_stage
  stage: Deploy
  dependencies: []

#

Notify Fail (dev):
  extends:
    - .base_notify_fail_stage
    - .notify_stage
    - .notify_dev

Notify Fail (prod):
  extends:
    - .base_notify_fail_stage
    - .notify_stage
    - .notify_prod

Notify Success (dev):
  extends:
    - .base_notify_success_stage
    - .notify_stage
    - .notify_dev

Notify Success (prod):
  extends:
    - .base_notify_success_stage
    - .notify_stage
    - .notify_prod

Delete useless k8s namespaces:
  extends:
    - .base_delete_useless_k8s_ns_stage
    - .notify_dev
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev2
  variables:
    K8S_NAMESPACE_PREFIX: cdtn-feature-
