#

.notify_stage: &notify_stage
  image: python:$PYTHON_VERSION
  variables:
    DEPLOY_ID_FILE: github_deploy_id
  before_script:
    - apk add --no-cache curl=7.64.0-r3
    - source .gitlab-ci/env.sh
  dependencies: []

#

Notify Starting Deployment:
  <<: *notify_stage
  stage: "Deploy"
  script:
    - sh ./.k8s/scripts/get-deploy-id.sh
    - echo "GitHub deployment id '$(cat github_deploy_id)'"
  artifacts:
    paths:
      - github_deploy_id

#

Notify Fail:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_failure
  dependencies:
    - Notify Starting Deployment
  script:
    - echo "Notify Failure to GitHub deployment id '$(cat $DEPLOY_ID_FILE)'"
    - export URL="http://${FRONTEND_HOST}"
    - sh ./.k8s/scripts/send-url.sh $(cat $DEPLOY_ID_FILE) failure

#

Notify Success:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_success
  dependencies:
    - Notify Starting Deployment
  script:
    - echo "Notify Success to GitHub deployment id '$(cat $DEPLOY_ID_FILE)'"
    - export URL="http://${FRONTEND_HOST}"
    - sh ./.k8s/scripts/send-url.sh $(cat $DEPLOY_ID_FILE) success

#
#
#

Release:
  stage: "Notify Finished Deployment"
  image: node:10.17.0-alpine3.10
  only:
    - master
  when: manual
  before_script:
    - apk add --no-cache git=2.22.0-r0
    - git checkout ${CI_COMMIT_REF_NAME}
    - git config user.name "${CI_GIT_AUTHOR_NAME}"
    - git config user.email "${CI_GIT_AUTHOR_EMAIL}"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - yarn --frozen-lockfile
  script:
    - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}

#
#
#

Production:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: manual
  only:
    - tags
  except:
    variables:
      - $PRODUCTION
  script:
    - echo "Put ${CI_COMMIT_REF_NAME}@${CI_COMMIT_SHORT_SHA} in production"
    - curl --request POST
      --form ref="${CI_COMMIT_REF_NAME}"
      --form token="${CI_DEPLOY_TRIGGER}"
      --form variables[PRODUCTION]="true"
      https://gitlab.factory.social.gouv.fr/api/v4/projects/51/trigger/pipeline
