#

.register_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

Register socialgouv/cdtn base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Register elasticsearch image:
  <<: *prepare_stage
  stage: "Prepare"
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch

Register nlp image:
  <<: *prepare_stage
  stage: "Prepare"
  variables:
    CONTEXT: packages/code-du-travail-nlp
    IMAGE_NAME: $CI_REGISTRY_IMAGE/nlp
  after_script:
    - >-
      if [[ "${BRANCH_NAME}" != "master" ]]; then
        docker pull "${IMAGE_NAME}:${CI_DEFAULT_BRANCH}"
        docker inspect --format='{{.RootFS}}' ${IMAGE_NAME}:${CI_DEFAULT_BRANCH} > MASTER_LAYERS
        docker inspect --format='{{.RootFS}}' ${IMAGE_NAME}:${CI_COMMIT_SHA} > COMMIT_LAYERS
        if cmp -s MASTER_LAYERS COMMIT_LAYERS ; then
          echo "No changes detected."
          touch "${CONTEXT}/${$CI_COMMIT_REF_SLUG}_USE_MASTER"
        else
          echo "Changes detected."
        fi
      fi
  artifacts:
    expire_in: 7 day
    paths:
      - packages/code-du-travail-nlp
