#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Register socialgouv/cdtn base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE
  only:
    changes:
      - yarn.lock
      - package.lock
      - packages/**/package.lock
      - packages/code-du-travail-data/**/*.js
  except:
    variables:
      - $PRODUCTION


Use latest socialgouv/cdtn base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE
  except:
    changes:
      - yarn.lock
      - package.lock
      - packages/**/package.lock
      - packages/code-du-travail-data/**/*.js
    variables:
      - $PRODUCTION
  script:
    #
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=$CI_COMMIT_REF_SLUG
      fi
    #
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $IMAGE_NAME:master || true
    #
    - echo "> docker tag $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA $IMAGE_NAME:$CI_COMMIT_SHA"
    - docker tag $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    #
    - docker tag $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA $IMAGE_NAME:$TAG
    - docker push $IMAGE_NAME:$TAG
#

Register elasticsearch image:
  <<: *prepare_stage
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch
