#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []
  except:
    variables:
      - $PRODUCTION

.cache_template: &cache_template
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/

Build yarn cache:
  <<: *prepare_stage
  image: node:10-alpine
  cache:
    <<: *cache_template
  script:
    - yarn --frozen-lockfile

Register elasticsearch image:
  <<: *prepare_stage
  extends: .base_register_stage
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch
