#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Register socialgouv/cdtn base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Register elasticsearch image:
  <<: *prepare_stage
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch
