#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []
  except:
    variables:
      - $PRODUCTION

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - cd /app

#

Lint @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/api lint

Lint @cdtn/ui-old:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/ui-old lint

Lint @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend lint

Lint @cdtn/data:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/data lint

Lint Dockerfiles:
  <<: *quality_stage
  image: hadolint/hadolint:latest-debian
  script:
    - |-
      for i in $(find . -name Dockerfile); do
        echo ""
        echo "[+] hadolint ${i}"
        hadolint ${i}
      done

Test @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend test --coverage

Test @cdtn/ui-old:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/ui-old test --coverage

Test @socialgouv/react-fiche-service-public:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-fiche-service-public test --coverage

Test @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  services:
    - $CI_REGISTRY_IMAGE/elasticsearch:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    ELASTICSEARCH_URL: http://localhost:$ELASTICSEARCH_PORT
    ELASTICSEARCH_LOG_LEVEL: info
  script:
    # NOTE(douglasduteil): the elasticsearch health check must be last
    # As we block the job waiting for elasticsearch to be up.
    - |-
      retry=60;
      while
        ! curl -sS "$ELASTICSEARCH_URL/_cat/health?h=status" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for Elasticsearch to go Green ($retry)" ; sleep 1 ; done ;
    #
    - yarn workspace @cdt/api test --coverage

Test @cdtn/data:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/data test
    - yarn workspace @cdt/data check-slugs
    - yarn workspace @cdt/data...datafiller test
