#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  needs:
    - Register socialgouv/cdtn base image
  before_script:
    - cd /app

#

Lint @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/api lint

Lint socialgouv/react-ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-ui lint

Lint @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend lint

Lint @cdtn/data:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/data lint

Lint Dockerfiles:
  <<: *quality_stage
  image: hadolint/hadolint:latest-debian
  script:
    - |-
      for i in $(find . -name Dockerfile); do
        echo ""
        echo "[+] hadolint ${i}"
        hadolint ${i}
      done

Test @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend test --coverage

Test @socialgouv/react-ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-ui test --coverage

Test @socialgouv/react-fiche-service-public:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-fiche-service-public test --coverage

Test @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  needs:
    - Register elasticsearch image
    - Register socialgouv/cdtn base image
  services:
    - $CI_REGISTRY_IMAGE/elasticsearch:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    ELASTICSEARCH_URL: http://localhost:$ELASTICSEARCH_PORT
  script:
    # NOTE(douglasduteil): the elasticsearch health check must be last
    # As we block the job waiting for elasticsearch to be up.
    - |-
      retry=120;
      while
        ! curl -sS "$ELASTICSEARCH_URL/_cat/health?h=status" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for Elasticsearch to go Green ($retry)" ; sleep 1 ; done ;
      echo $retry
    #
    - yarn workspace @cdt/api test --coverage

Test @cdtn/data:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/data test
    - yarn workspace @cdt/data check-slugs
    - yarn workspace @cdt/data...datafiller test

Test @cdtn/frontend SDR data:
  <<: *quality_stage
  image: alpine:3.10
  allow_failure: true
  before_script:
    - apk add --no-cache jq=1.6-r0 wget=1.20.3-r0
  script:
    - |-
      jq ".[].url" ./packages/code-du-travail-frontend/src/data/services-de-renseignement.json | xargs -n 1 wget  --spider
