#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when updating Elasticloud data
      - $UPDATE_ES_INDEX
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  needs:
    - Register socialgouv/cdtn base image
  before_script:
    - cd /app

#

Lint socialgouv/react-ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/cdtn-ui lint

Lint socialgouv/react-fiche-service-public:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-fiche-service-public lint

Lint Dockerfiles:
  <<: *quality_stage
  image: hadolint/hadolint
  script:
    - |-
      for i in $(find . -name Dockerfile); do
        echo ""
        echo "[+] hadolint ${i}"
        hadolint ${i}
      done

Test @socialgouv/cdtn-ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/cdtn-ui test

Test @socialgouv/react-fiche-service-public:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-fiche-service-public test

Test @cdtn/data:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/data test
    - yarn workspace @cdt/data check-slugs
