#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - cd /app

.python_based_stage: &python_based_stage
  image: python:$PYTHON_VERSION
  variables:
    PIPENV_VENV_IN_PROJECT: 1
    PIPENV_IGNORE_VIRTUALENVS: 1
    PYTHONPATH: .
  before_script:
    - cd packages/code-du-travail-data
    - apk add --no-cache build-base
    - python -m venv venv
    - . venv/bin/activate
    - pip install pylint
    - pip install -r requirements.txt

#

Lint @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/api lint

Lint @cdtn/ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/ui lint

Lint @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend lint

Lint @cdtn/data:
  <<: *quality_stage
  <<: *python_based_stage
  script:
    - pylint --output-format=colorized search

#

Test @cdtn/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/frontend test --coverage

Test @cdtn/ui:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @cdt/ui test --coverage

Test @socialgouv/react-fiche-service-public:
  <<: *quality_stage
  <<: *master_based_stage
  script:
    - yarn workspace @socialgouv/react-fiche-service-public test --coverage

Test @cdtn/api:
  <<: *quality_stage
  <<: *master_based_stage
  services:
    - $CI_REGISTRY_IMAGE/elasticsearch:$ELK_STACK_VERSION
  variables:
    GIT_STRATEGY: none
    ELASTICSEARCH_URL: http://localhost:$ELASTICSEARCH_PORT
    ELASTICSEARCH_LOG_LEVEL: info
  script:
    # NOTE(douglasduteil): the elasticsearch health check must be last
    # As we block the job waiting for elasticsearch to be up.
    - |-
      retry=60;
      while
        ! curl -sS "$ELASTICSEARCH_URL/_cat/health?h=status" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for Elasticsearch to go Green ($retry)" ; sleep 1 ; done ;
    #
    - yarn workspace @cdt/api test --coverag

Test @cdtn/data:
  <<: *quality_stage
  <<: *python_based_stage
  script:
    - python search/indexing/document_slug_checker.py -v
