Register api image:
  extends:
    - .register
  stage: "Register Data API"
  variables:
    CONTEXT: packages/code-du-travail-api
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

#

Register data image:
  extends:
    - .register
  stage: "Register Data API"
  services:
    - name: docker:19-dind
    - name: $CI_REGISTRY_IMAGE/nlp:$CI_COMMIT_SHA
      alias: nlp

  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
      --build-arg NLP_URL=http://nlp:${NLP_PORT}
      --network=host
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data
  before_script:
    - |-
      echo "connecting to http://nlp:${NLP_PORT}";

      retry=60;
      while
        ! wget --spider "http://nlp:${NLP_PORT}/api/ready" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for nlp api to be ready ($retry)" ; sleep 5 ; done ;
      [ "$retry" -eq "-1" ] && exit 1

#

Register frontend image:
  extends: .register
  stage: "Register Frontend"
  environment:
    name: fabrique-dev
  variables:
    CONTEXT: packages/code-du-travail-frontend
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
      --build-arg API_URL=${API_URL}
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend
  before_script:
    - source ./.gitlab-ci/env.sh
    - |-
      retry=60;
      while
        ! wget -q -O - "$@" "${API_URL}/api/v1/version"  | grep "${COMMIT}" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for data API to be ready" ; sleep 3 ; done ;
      [ "$retry" -eq "-1" ] && exit 1
