#

.register_stage: &register_stage
  extends: .base_register_stage
  stage: "Registration"
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

#

Register socialgouv/cdtn base image:
  <<: *register_stage
  stage: "Prepare"
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Register elasticsearch image:
  <<: *register_stage
  stage: "Prepare"
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch

#

Register data image:
  <<: *register_stage
  stage: "Post Registration"
  needs:
    - Register nlp image
  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data
