#

.register_stage: &register_stage
  extends: .base_register_stage
  stage: "Registration"
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

#

Register socialgouv/cdtn base image:
  <<: *register_stage
  stage: "Prepare"
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Register elasticsearch image:
  <<: *register_stage
  stage: "Prepare"
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch

Register nlp image:
  <<: *register_stage
  stage: "Prepare"
  variables:
    CONTEXT: packages/code-du-travail-nlp
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/nlp

#

Register api image:
  <<: *register_stage
  variables:
    CONTEXT: packages/code-du-travail-api
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

Register frontend image:
  <<: *register_stage
  variables:
    CONTEXT: packages/code-du-travail-frontend
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend

Register data image:
  <<: *register_stage
  services:
    - name: docker:19-dind
    - name: $CI_REGISTRY_IMAGE/nlp:$CI_COMMIT_SHA
      alias: nlp
  needs:
    - Register nlp image
    - Register socialgouv/cdtn base image

  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
      --build-arg NLP_URL=http://nlp:${NLP_PORT}
      --network=host
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data
  before_script:
    - |-
      echo "connecting to http://nlp:${NLP_PORT}";

      retry=60;
      while
        ! wget --spider "http://nlp:${NLP_PORT}/api/ready" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for nlp api to be ready ($retry)" ; sleep 1 ; done ;
      [ "$retry" -eq "-1" ] && exit 1

#
