#

.build_and_push_stage: &build_and_push_stage
  extends: .base_register_stage
  stage: "Registration"

Register api image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-api
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

Register frontend image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-frontend
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend

Register nlp image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-nlp
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
      --build-arg SUGGEST_DATA_URL=$SUGGEST_DATA_URL
    IMAGE_NAME: $CI_REGISTRY_IMAGE/nlp
