#

.register-stage: &register_stage
  extends: .docker_stage
  stage: "Registration"
  dependencies: []
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    # NOTE(douglasduteil): do not fail if no previous sha image exist
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
  script:
    - echo "Build $IMAGE_NAME:$CI_COMMIT_SHA from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA"
    - docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
    - docker push $IMAGE_NAME

#

Register api image:
  <<: *register_stage
  variables:
    CONTEXT: packages/code-du-travail-api
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

Register frontend image:
  <<: *register_stage
  variables:
    CONTEXT: packages/code-du-travail-frontend
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend

Register data image:
  <<: *register_stage
  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data
