#

.scan_stage: &scan_stage
  stage: "Vuln scanner"
  dependencies: []
  before_script:
    - source .gitlab-ci/env.sh
  except:
    variables:
      - $PRODUCTION

Snyk docker scan:
  <<: *scan_stage
  image: snyk/snyk-cli:docker
  allow_failure: true
  services:
    - docker:$DOCKER_VERSION-dind
  script:
    - ./scripts/snyk-docker-scan.sh

