Export storage to prod:
  stage: .post
  when: manual
  extends:
    - .base_deploy_kosko_stage
  environment:
    name: prod2
  rules:
    - if: '($CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "web") && $UPDATE_ES_INDEX == "PROD"'
      when: always
  environment:
    name: preprod-dev2
  variables:
    # storage copy
    SOURCE_CONTAINER: "cdtn"
    SOURCE_SERVER: "dev"
    DESTINATION_CONTAINER: "cdtn"
    DESTINATION_SERVER: "prod"
    # kosko options
    KOSKO_GENERATE_ARGS: --env prod restore
