Export storage to prod:
  stage: .post
  extends:
    - .base_deploy_kosko_stage
  environment:
    name: prod2
  dependencies: []
  allow_failure: true
  rules:
    # When triggered by cdtn-admin or GitLab Index
    - if: '($CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "web") && $UPDATE_ES_INDEX == "PROD"'
      when: always
    # When deploying new CDTN
    - if: $PRODUCTION
      when: always
    - when: manual
  variables:
    # storage copy
    SOURCE_CONTAINER: "cdtn"
    SOURCE_SERVER: "dev"
    DESTINATION_CONTAINER: "cdtn"
    DESTINATION_SERVER: "prod"
    # kosko options
    KOSKO_GENERATE_ARGS: --env prod restore
