Fiches MT update:
  stage: FichesMT
  image: node:12.14-alpine3.10
  only:
    changes:
      - packages/code-du-travail-data/dataset/fiches_ministere_travail/ministere-travail-liste-fiches.json
  except:
    - master
    - tags
  before_script:
    - apk update && apk add git curl jq
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - git fetch origin +refs/pull/*/merge:refs/remotes/origin/pr/*
  script:
    - export PR_ID=$(git ls-remote origin refs/pull/[0-9]*/head | grep ${CI_COMMIT_SHA} | cut -d '/' -f3 | tail -1)
    - yarn
    - yarn workspace @cdt/data...fiches_ministere_travail run start
    - yarn workspace @cdt/data...fiches_ministere_travail run updateTheme
    - |
      yarn workspace @cdt/data...fiches_ministere_travail -s run report | \
      jq --ascii-output --slurp --raw-input '{"body": .}' | \
       curl -i -X POST \
         --header 'content-type: application/json' \
         -d @- https://${GITHUB_TOKEN}@api.github.com/repos/${CI_PROJECT_PATH}/issues/${PR_ID}/comments
    - "git commit -am 'fix: update fiches-MT data'"
    - git push origin HEAD:${CI_COMMIT_REF_NAME}

    # Stop processing further
    - exit 1
