.deploy-kibana-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  script:
  - kubectl apply -f k8s/kibana/deployment-kibana.yml
  - kubectl apply -f k8s/kibana/service-kibana.yml
  allow_failure: false
