.deploy-code-du-travail-frontend-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - export HASH_BRANCH_NAME=-$BRANCH_HASH
  #
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-frontend/deployment-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/deployment-cdtn-frontend.yml
  - envsubst < k8s/code-du-travail-frontend/service-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/service-cdtn-frontend.yml
  - envsubst < k8s/code-du-travail-frontend/ingress-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/ingress-cdtn-frontend.yml
  #
  - kubectl apply -f k8s/code-du-travail-frontend/deployment-cdtn-frontend.yml
  - kubectl apply -f k8s/code-du-travail-frontend/service-cdtn-frontend.yml
  - kubectl apply -f k8s/code-du-travail-frontend/ingress-cdtn-frontend.yml
  - echo "CDTN frontend available at - ${FRONTEND_HOST}"
  allow_failure: false

.deploy-code-du-travail-frontend-prod-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - /apps/create-kubeconfig.sh
  #
  - envsubst < k8s/code-du-travail-frontend/deployment-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/deployment-cdtn-frontend.yml
  - envsubst < k8s/code-du-travail-frontend/service-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/service-cdtn-frontend.yml
  - envsubst < k8s/code-du-travail-frontend/ingress-code-du-travail-frontend.yml > k8s/code-du-travail-frontend/ingress-cdtn-frontend.yml
  #
  - kubectl apply -f k8s/code-du-travail-frontend/deployment-cdtn-frontend.yml
  - kubectl apply -f k8s/code-du-travail-frontend/service-cdtn-frontend.yml
  - kubectl apply -f k8s/code-du-travail-frontend/ingress-cdtn-frontend.yml
  - echo "CDTN frontend available at - ${FRONTEND_HOST}"
  allow_failure: false
