.deploy-code-du-travail-frontend-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
  - /apps/create-kubeconfig.sh
  - kubectl apply -f k8s/code-du-travail-code-du-travail-frontend/deployment-code-du-travail-frontend.yml
  - kubectl apply -f k8s/code-du-travail-code-du-travail-frontend/service-code-du-travail-frontend.yml
  - kubectl apply -f k8s/code-du-travail-code-du-travail-frontend/ingress-code-du-travail-frontend.yml
  allow_failure: false
