.k8s-deploy-elasticsearch-dev:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/elasticsearch/configmap.yml > ./configmap.yml
    - envsubst < ./.k8s/elasticsearch/service.yml > ./service.yml
    - envsubst < ./.k8s/elasticsearch/statefulset.dev.yml > ./statefulset.yml
    - env
    - cat ./statefulset.yml
    #
    - kubectl apply -f ./configmap.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./statefulset.yml

.k8s-deploy-elasticsearch-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/elasticsearch/service.yml > ./service.yml
    - envsubst < ./.k8s/elasticsearch/statefulset.prod.yml > ./statefulset.yml
    #
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./statefulset.yml
