---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${K8S_NAMESPACE}-es-config-${BRANCH_HASH}
  labels:
    app: ${K8S_NAMESPACE}-es-config-${BRANCH_HASH}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
data:
  elasticsearch.yml: |
    cluster.name: "${K8S_NAMESPACE}-data-elasticsearch"
    node.name: "${K8S_NAMESPACE}-data-elasticsearch-single-node"
    network.host: 0.0.0.0
    discovery.type: single-node
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.ml.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
  ES_JAVA_OPTS: -Xms256m -Xmx256m
