---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
  template:
    metadata:
      labels:
        app: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
        git/branch: ${BRANCH_NAME}
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - image: ${IMAGE_NAME}:${IMAGE_TAG}
          name: ${K8S_NAMESPACE}-${CONTEXT}
          ports:
            - containerPort: ${PORT}
          livenessProbe:
            httpGet:
              path: /api/v1/version
              port: ${PORT}
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/version
              port: ${PORT}
            initialDelaySeconds: 3
            periodSeconds: 5
          env:
          - name: PORT
            value: "${PORT}"
          - name: APM_SERVER_ACTIVE
            value: "${APM_SERVER_ACTIVE}"
          - name: APM_SERVER_URL
            value: "${APM_SERVER_URL}"
          - name: ELASTICSEARCH_LOG_LEVEL
            value: "${ELASTICSEARCH_LOG_LEVEL}"
          - name: ELASTICSEARCH_URL
            value: "${ELASTICSEARCH_URL}"
          - name: VERSION
            value: "${VERSION}"
