#

Build nlp:
  stage: Prepare
  dependencies: []
  image: python:3.7-slim-buster
  interruptible: true
  variables:
    CONTEXT: code-du-travail-nlp
    #
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/pip
    PYTHONPATH: ${CI_PROJECT_DIR}/packages/${CONTEXT}
    PYTHONUSERBASE: "${CI_PROJECT_DIR}/python_user_packages"
  script:
    - cd ./packages/${CONTEXT}
    - export PATH="${PATH}:${PYTHONUSERBASE}/bin"
    - pip install --upgrade pip
    - pip install --user -r requirements.txt
    - python ./scripts/dump.py
  artifacts:
    expire_in: 30 mins
    paths:
      - packages/${CONTEXT}/data/dump.tf.json
