#

Install nlp:
  extends: .prepare_stage
  image: python:3.7-slim-buster
  interruptible: true
  variables:
    CONTEXT: code-du-travail-nlp
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/packages/${CONTEXT}/.cache/pip"
  cache:
    key: "install-nlp-${CI_COMMIT_REF_SLUG}"
    paths:
      - packages/${CONTEXT}/.cache/pip
  script:
    - cd packages/${CONTEXT}
    - pip install --user -r requirements.txt
  artifacts:
    expire_in: 30 mins
    paths:
      - $HOME/.local

#

Build @cdt/nlp:
  extends: .quality_stage
  stage: "Build"
  dependencies:
    - Build @cdt/data
    - Install nlp
  needs:
    - Build @cdt/data
    - Install data
    - Install nlp
  variables:
    PYTHONPATH: "${CI_PROJECT_DIR}/packages/code-du-travail-nlp"
  image: python:3.7-slim-buster
  script:
    # - find packages/code-du-travail-api/src -type f \( -exec sha1sum {} \; \) | sha1sum
    # - sha1sum yarn.lock packages/${CONTEXT}/package.json > PACKAGE_SHA
    # - cat PACKAGE_SHA
    # - >-
    #   if [[ -d node_modules ]] && cmp -s PACKAGE_SHA SHA ; then
    # Copy the `@cdt/data` artefact to the nlp data directory
    - cp ./packages/code-du-travail-data/dist/dump.data.json
        ./packages/code-du-travail-nlp/data/dump.json
    #
    - cd packages/${CONTEXT}
    - python ./scripts/dump.py
  artifacts:
    expire_in: 30 mins
    paths:
      - packages/code-du-travail-nlp/data/dump.tf.json

#

Register nlp image:
  extends:
    - .base_register_stage
    - .register_stage
  variables:
    CONTEXT: packages/code-du-travail-nlp
    DOCKER_BUILD_ARGS: >-
      --build-arg SUGGEST_DATA_URL=$SUGGEST_DATA_URL
    IMAGE_NAME: $CI_REGISTRY_IMAGE/nlp

#

.deploy_nlp_stage:
  extends:
    - .base_deploy_nodejs_chart_stage
    - .deploy_stage
    - .dev_stage
  variables:
    IMAGE_TAG: master
    PORT: ${NLP_PORT}
    CONTEXT: nlp
    VALUES_FILE: ./.k8s/nlp.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${NLP_HOST}

#

Deploy @cdtn/nlp (dev):
  extends:
    - .deploy_nlp_stage
    - .dev_stage

# Deploy @cdtn/nlp (prod):
#   extends:
#     - .deploy_nlp_stage
#     - .dev_stage
