.k8s-deploy-frontend:
  extends: .base_docker_kube_image_stage
  script:
    #
    - envsubst < ./.k8s/frontend/deployment${SUFFIX}.yml > ./deployment.yml
    - envsubst < ./.k8s/frontend/service.yml > ./service.yml
    - envsubst < ./.k8s/frontend/ingress${SUFFIX}.yml > ./ingress.yml
    #
    - |
      if [ -n "${COMMIT_TAG}" ]; then
        envsubst < ./.k8s/certificate/certificate.yml > ./certificate.yml;
        kubectl apply -f ./certificate.yml;
      fi
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml
