---
include:
  - project: SocialGouv/gitlab-ci-yml
    file:
      - /base_register_docker_stage.yml
    ref: v20.7.14
  #
  - /infra/logger/.gitlab-ci.logger-lib.yml

#
#
#

variables:
  #
  PACKAGE: code-du-travail-api
  PACKAGE_CWD: packages/${PACKAGE}
  #
  CACHE_FALLBACK_KEY: ${PACKAGE}-${CI_JOB_NAME}-${CI_DEFAULT_BRANCH}
  MONOREPO_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/monorepo"
  #
  GIT_STRATEGY: fetch
  GIT_DEPTH: 3

before_script:
  - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
  - sh ./.gitlab-ci/monorepo.sh skip && exit 0 || true
  - cd "${PACKAGE_CWD}"

Install:
  stage: .pre
  image: node:14.16-alpine3.13
  needs: []
  cache:
    key: ${PACKAGE}-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache
      - ${PACKAGE_CWD}/node_modules
      - node_modules
  before_script:
    - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
    - sh ./.gitlab-ci/monorepo.sh has-changed
        --find-ignore "*/node_modules/*"
        ${PACKAGE_CWD} || true
    - |
      sh ./.gitlab-ci/monorepo.sh skip &&
        rm -rf .cache/yarn "${PACKAGE_CWD}/node_modules" node_modules;
        exit 0;
      } || true
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
    - yarn exec yarn-workspace-focus-install -- --cwd ${PACKAGE_CWD} -- --frozen-lockfile --prefer-offline
  artifacts:
    expire_in: 1 week
    paths:
      - ${MONOREPO_CACHE_FOLDER}/skip
      - ${PACKAGE_CWD}/node_modules
      - node_modules

#
#
#

Build:
  stage: build
  image: node:14.16-alpine3.13
  cache:
    key: ${PACKAGE}-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - ${PACKAGE_CWD}/dist
  variables:
    CI_DEBUG_TRACE: "true"
  needs:
    - job: Install
      artifacts: true
    - job: 🚚 logger
      artifacts: true
  before_script:
    - wget -qO ./.gitlab-ci/monorepo.sh https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/master/monorepo.sh
    - sh ./.gitlab-ci/monorepo.sh skip && exit 0 || true
    - cd "${PACKAGE_CWD}"
  script:
    # NOTE(douglasduteil): ensure to have clean build
    - rm -rf lib
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - ${PACKAGE_CWD}/dist

#
#
#

Lint:
  stage: build
  image: node:14.16-alpine3.13
  needs:
    - job: Install
      artifacts: true
  script:
    - yarn lint

Lint Dockerfiles:
  stage: build
  needs: []
  image: hadolint/hadolint:v1.23.0-alpine
  script:
    - hadolint ./Dockerfile

#
#
#

Test:
  stage: build
  image: node:14.16-alpine3.13
  needs:
    - job: Install
      artifacts: true
    - job: 🚚 logger
      artifacts: true
    - job: Register elasticsearch image
  services:
    - name: $CI_REGISTRY_IMAGE/elasticsearch:$CI_COMMIT_SHA
      alias: elasticsearch
      command:
        - "bin/elasticsearch"
        - "-Expack.security.enabled=false"
        - "-Ediscovery.type=single-node"
  variables:
    ELASTICSEARCH_URL: http://elasticsearch:$ELASTICSEARCH_PORT
    # HACK(douglasduteil): make ES not that memory hungry
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
  script:
    # NOTE(douglasduteil): the elasticsearch health check must be last
    # As we block the job waiting for elasticsearch to be up.
    - |-
      echo "connecting to ${CI_REGISTRY_IMAGE}/elasticsearch:${CI_COMMIT_SHA}";
      echo "${ELASTICSEARCH_URL}";
      retry=60;
      while
        ! wget -q -O - "$@" "${ELASTICSEARCH_URL}/_cat/health?h=status" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for Elasticsearch to go Green (${retry})" ; sleep 1 ; done ;
      [ "${retry}" -eq "-1" ] && exit 1
    #
    - yarn test --coverage

#
#
#

Register elasticsearch image:
  stage: .pre
  needs:  []
  extends:
    - .base_register_docker_stage
  before_script:
    - cd "${CI_PROJECT_DIR}"
  variables:
    CONTEXT: ./docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch

Register:
  stage: test
  extends:
    - .base_register_docker_stage
  needs:
    - job: Lint Dockerfiles
    - job: Build
      artifacts: true
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api
