.deploy-code-du-travail-data-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  script:
  - kubectl apply -f k8s/code-du-travail-data/deployment-code-du-travail-data.yml
  allow_failure: false
