---
apiVersion: v1
kind: Pod
metadata:
  name: cdtn-data${HASH_BRANCH_NAME}
  labels:
    app: cdtn-data${HASH_BRANCH_NAME}
    branch: cdtn${HASH_BRANCH_NAME}
spec:
  containers:
  - name: cdtn-data${HASH_BRANCH_NAME}
    image: ${CDTN_REGISTRY}/data:${IMAGE_TAG}
    env:
    - name: ELASTICSEARCH_URL
      value: "http://${ELASTICSEARCH_HOST}"
  restartPolicy: Never
  initContainers:
  - name: wait-for-elasticsearch
    image: alpine
    imagePullPolicy: Always
    command:
    - sh
    - -c
    - |
      apk --no-cache  --update add curl
      while [[ $(curl --silent --output /dev/null --request GET --write-out "%{http_code}" "http://elasticsearch${HASH_BRANCH_NAME}:${ES_PORT}") -ne 200 ]]; do
        echo "Not ready"
        sleep 5s
      done
      echo Ready
